# Use Auto DevOps pipeline
# https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Auto-DevOps.gitlab-ci.yml
include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  # Disable some Auto DevOps tests
  BROWSER_PERFORMANCE_DISABLED: 1
  CODE_QUALITY_DISABLED: 1
  LICENSE_MANAGEMENT_DISABLED: 1
  DISABLE_LICENSE_SCANNING: 1
  SAST_DISABLED: 1
  SECRET_DETECTION_DISABLED: 1
  DAST_DISABLED: 1
  PERFORMANCE_DISABLED: 1

  # GitLab CI configuration
  # TEST_DISABLED: 1
  POSTGRES_ENABLED: "false"
  STAGING_ENABLED: 1
  KUBE_INGRESS_BASE_DOMAIN: leaf-vre.org
  KUBE_CONTEXT: "calincs/gitlab-agents:leaf-agent"
  KUBE_NAMESPACE: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG

  K8S_SECRET_GA_MEASUREMENT_ID: $GA_MEASUREMENT_ID
  K8S_SECRET_KEYCLOAK_URL: $KEYCLOAK_URL
  K8S_SECRET_AUTH_API_URL: $AUTH_API_URL

  # Disable the le-<project-id> host
  # https://gitlab.com/gitlab-org/cluster-integration/auto-deploy-image/-/blob/381abf6d6bffe46c6f88ca995920a5ca9ddd2a49/src/bin/auto-deploy#L354
  AUTO_DEVOPS_COMMON_NAME: ""

# Only rebuild node_modules if package.json changes
cache:
  key:
    files:
      - package.json
  paths:
    - node_modules

# Overwrite test job
test:
  stage: test
  image: node:20.9-alpine
  script:
    - npm install
    - npm test
  needs:
    - build

# Template to override common stage/prod parameters
.deployment: &deployment
  environment:
    url: http://leaf-writer.$KUBE_INGRESS_BASE_DOMAIN

# override some staging parameters
staging:
  variables:
    KUBE_INGRESS_BASE_DOMAIN: stage.lincsproject.ca
    KUBE_CONTEXT: "calincs/gitlab-agents:stage-agent"
    KUBE_NAMESPACE: $CI_PROJECT_NAME-$CI_PROJECT_ID-staging
  <<: *deployment

# override some production parameters
production_manual:
  environment:
    name: production
  id_tokens:
    NPM_ID_TOKEN:
      aud: "npm:registry.npmjs.org"
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  variables:
    KUBE_INGRESS_BASE_DOMAIN: leaf-vre.org
    KUBE_CONTEXT: "calincs/gitlab-agents:leaf-agent"
    KUBE_NAMESPACE: $CI_PROJECT_NAME-$CI_PROJECT_ID-production
  before_script:
    - apk add --update npm
    - npm ping
    - npm i -g changeset typescript webpack shelljs webpack-cli
    - npm ci
    - npm run release
  <<: *deployment
