FROM node:16.14-alpine

# Needed because some dependencies are fetch from git and alpine does not come with git
RUN apk add --no-cache git

ARG AUTHORIZATION_CALLBACK_URL
ARG GA_MEASUREMENT_ID

WORKDIR /app

COPY . .

CMD [ "npm", "--prefix", "packages/standalone", "run", "dev:docker-server" ]

EXPOSE 3000