import CitationDialog from './CitationDialog';
import CorrectionDialog from './CorrectionDialog';
import DateDialog from './DateDialog';
import KeywordDialog from './KeywordDialog';
import LinkDialog from './LinkDialog';
import NoteDialog from './NoteDialog';
import OrganizationDialog from './OrganizationDialog';
import PersonDialog from './PersonDialog';
import PlaceDialog from './PlaceDialog';
import RsDialog from './RsDialog';
import TitleDialog from './TitleDialog';
export { CitationDialog };
export { DateDialog };
export { KeywordDialog };
export { LinkDialog };
export { NoteDialog };
export { OrganizationDialog };
export { PersonDialog };
export { PlaceDialog };
export { RsDialog };
export { TitleDialog };
declare const _default: {
    citation: typeof CitationDialog;
    correction: typeof CorrectionDialog;
    date: typeof DateDialog;
    keyword: typeof KeywordDialog;
    link: typeof LinkDialog;
    note: typeof NoteDialog;
    organization: typeof OrganizationDialog;
    person: typeof PersonDialog;
    place: typeof PlaceDialog;
    rs: typeof RsDialog;
    title: typeof TitleDialog;
};
export default _default;
//# sourceMappingURL=index.d.ts.map