import { Context } from '../';
import type { EntityLink, EntityLookupDialogProps } from '../../components/entityLookups/types';
import type { PopupProps } from '../../components/popup';
import { ContextMenuState, PaletteMode } from '../../types';
export declare const onInitializeOvermind: ({ actions }: Context, overmind: any) => void;
export declare const setThemeAppearance: ({ state, actions }: Context, value: PaletteMode) => void;
export declare const setDarkMode: ({ state }: Context, value: boolean) => void;
export declare const closeContextMenu: ({ state }: Context) => void;
export declare const showContextMenu: ({ state }: Context, value: ContextMenuState) => void;
export declare const updateTitle: ({ state }: Context, title: string) => void;
export declare const resetPreferences: () => void;
export declare const openPopup: ({ state }: Context, props: Omit<PopupProps, 'open'>) => void;
export declare const closePopup: ({ state }: Context, id: string) => void;
export declare const openEditSourceDialog: ({ state }: Context, content: string) => void;
export declare const closeEditSourceDialog: ({ state }: Context) => void;
export declare const processEditSource: ({ state, actions }: Context, newContent: string) => void;
export declare const openEntityLookupsDialog: ({ state }: Context, props: Omit<EntityLookupDialogProps, 'open'>) => void;
export declare const closeEntityLookupsDialog: ({ state: { ui } }: Context, link?: EntityLink | Pick<EntityLink, 'query' | 'type'>) => void;
export declare const switchLanguage: ({ state }: Context, value: string) => string;
export declare const openSettingsDialog: ({ state }: Context) => void;
export declare const closeSettingsDialog: ({ state }: Context) => void;
//# sourceMappingURL=actions.d.ts.map