/**
 * Tag Appearance lists only semantic / annotation tags used in the document body.
 * Metadata (inside teiHeader — also skipped when counting stats) and TEI
 * scaffolding (div, p, list, …) are excluded.
 */

/** TEI shell, metadata containers, and stand-off lists — never shown. */
const METADATA_AND_SHELL_TAGS = [
  'TEI',
  'teiHeader',
  'text',
  'front',
  'body',
  'back',
  'fileDesc',
  'titleStmt',
  'editionStmt',
  'publicationStmt',
  'sourceDesc',
  'encodingDesc',
  'projectDesc',
  'appInfo',
  'application',
  'profileDesc',
  'langUsage',
  'language',
  'revisionDesc',
  'change',
  'standOff',
  'listPerson',
  'listPlace',
  'listOrg',
  'listBibl',
  'person',
  'place',
  'org',
  'bibl',
  'xenoData',
  // Metadata leaf elements (header counts are skipped too; belt-and-suspenders)
  'author',
  'editor',
  'publisher',
  'distributor',
  'authority',
  'availability',
  'licence',
  'pubPlace',
  'extent',
  'idno',
  'edition',
  'funder',
  'sponsor',
  'principal',
  'resp',
  'respStmt',
  'noteStmt',
  'seriesStmt',
  'samplingDecl',
  'rendition',
  'keywords',
  'taxonomy',
  'textClass',
  'classCode',
  'catDesc',
  'creation',
  'titlePage',
  'titlePart',
  'docAuthor',
  'docDate',
  'docEdition',
  'docImprint',
  'docTitle',
  'monogr',
  'imprint',
  'biblStruct',
  'biblFull',
  'biblScope',
  'msDesc',
  'msIdentifier',
  'repository',
  'collection',
  'msName',
  'msContents',
  'physDesc',
  'history',
  'additional',
  'adminInfo',
  'publication',
  'provenance',
] as const;

/** Block/layout scaffolding — not user-facing annotation types. */
const STRUCTURAL_TAGS = [
  'p',
  'ab',
  'head',
  'label',
  'div',
  'div1',
  'div2',
  'div3',
  'div4',
  'div5',
  'div6',
  'div7',
  'lg',
  'l',
  'list',
  'item',
  'figure',
  'lb',
  'group',
  'sp',
  'cit',
  'q',
  'eg',
  'pb',
  'milestone',
  'floatingText',
  'table',
  'row',
  'cell',
  'said',
  'stage',
  'castList',
  'castItem',
  'byline',
  'dateline',
  'signed',
  'salute',
  'trailer',
  'opener',
  'closer',
  'argument',
  'epigraph',
  'listWit',
  'wit',
  'witness',
  'zone',
  'surface',
  'graphic',
  'media',
  'formula',
  'anchor',
  'ptr',
  'link',
  'linkGrp',
  'join',
  'joinGrp',
  'alt',
  'altGrp',
  'spanGrp',
  'interp',
  'interpGrp',
  'relation',
  'relationGrp',
  'listChange',
] as const;

export const TAG_APPEARANCE_EXCLUDED_TAGS = new Set<string>([
  ...METADATA_AND_SHELL_TAGS,
  ...STRUCTURAL_TAGS,
]);

/**
 * Inline editorial / correction tags — pill text colour works in show-tags mode,
 * but full-element background highlighting does not apply usefully.
 */
export const TAG_APPEARANCE_TEXT_ONLY_TAGS = new Set([
  'choice',
  'sic',
  'corr',
  'supplied',
  'surplus',
  'reg',
  'gap',
  'add',
  'del',
  'subst',
]);

export const isTagAppearanceExcluded = (tagName: string): boolean =>
  TAG_APPEARANCE_EXCLUDED_TAGS.has(tagName);

export const isTagAppearanceCandidate = (tagName: string, count: number): boolean =>
  count > 0 && !isTagAppearanceExcluded(tagName);

export const tagAppearanceSupportsHighlight = (tagName: string): boolean =>
  !TAG_APPEARANCE_TEXT_ONLY_TAGS.has(tagName);
