import { reconcile } from '../services/lincs-api';
import type { NamedEntityType } from '../types';
import type { AuthorityLookupResult } from '../types/authority';
import { AuthorityCache } from './authorityCache';
import {
  ENTITY_KINDS,
  entityElements,
  parseIsoYear,
  TAG_TO_KIND,
  type AuthorityId,
  type AuthoritySourcedFields,
  type EntityKind,
} from './entities';
import { formatNorbertAuthorityValue } from './norbertAuthorityId';
import {
  biographicalYearsFromMetadata,
  filterYearsFromMetadata,
  floruitYearsFromMetadata,
  isFilterOnlyDateSource,
  scrubIndexYearFloruitClue,
} from './personDates';
import { linkedCentralIds } from './bridgeInbox';
import type { EntityStore } from './entityStore';
import { textWithoutHiddenReadings } from './hiddenChoiceText';
import { adoptFromCentralSqlite } from './sqliteBridgeOps';
import {
  extractWikidataIdsFromText,
  fetchWikidataGivenFamilyNames,
  fetchWikidataTypedNames,
  filterReconcileByExactSurface,
  isLatinSurface,
  preferredLabelForLang,
  stringsMatchExactly,
  wikidataLabelsByQid,
  type WikidataGivenFamilyNames,
} from './disambiguationMatch';
import { normalizeNameType, normalizeTypedNamesForIntake, type NameTypeId } from './nameTypes';
import {
  enrichCandidatesWithBdrcWikidataConcordance,
  emptyBdrcWikidataIndex,
  fetchBdrcIdsForQids,
  loadBdrcWikidataConcordance,
  mergeBdrcWikidataIndexes,
  qidsMissingBdrcLink,
} from './bdrcWikidataConcordance';
import {
  authorityIdsFromPackCrosswalk,
  enrichCandidatesWithViafWikidataConcordance,
  loadViafWikidataConcordance,
  normalizeViafId,
  normalizeWikidataQid,
} from './viafWikidataConcordance';
import {
  isEastAsianCalendarLanguageCode,
  isLatnLang,
  isTibetanLanguageCode,
  textMatchesProjectScript,
} from '../utilities/languageCodes';
import { autoRomanizeForKind, romanizeFromAuthorityMetadata } from '../utilities/romanize';
import type { WikidataFetchFn } from './wikidataDates';
import { fetchWikidataLifespan, prefixDescriptionWithLifespan } from './wikidataDates';
import { fetchDilaPlaceDetail, type DilaFetchFn } from './dilaPlaceDetail';
import { DilaPlaceDetailCache } from './dilaPlaceDetailCache';
import { wikidataQidsMatchingKind } from './wikidataKindFilter';
import { packIdsForEntityType, searchPackRows } from '../services/authority-pack-lookup';
import { viafIdsOnCandidate, viafNativeHeadingForId, type ViafFetchFn } from './viafNativeHeadings';
import { BDRC_SHOW_URL, extractBdrcId, normalizeBdrcId } from './bdrcIds';

export { BDRC_PURL, BDRC_SHOW_URL, extractBdrcId, normalizeBdrcId } from './bdrcIds';
import { AUTHORITY_PACKS } from './packPaths';
import {
  normalizeDateRangeFilter,
  parseAuthorityNdjson,
  preciseDateExceedsExcludeLimit,
  type AuthorityPackContent,
  type DateRangeFilter,
} from './packLoader';
import type { AuthorityCandidate } from './authority';
import type { AuthorityPackId } from './packPaths';
import { centroidOf, haversineDistanceKm } from './geoCluster';
import { loadHuckbotGlossIndex, loadMaxiRicciGlossIndex } from './officeGlossLookup';

export interface DisambiguationCandidate {
  id: string;
  label: string;
  description?: string;
  sources: string[];
  uri?: string;
  authorityIds?: AuthorityId[];
  authoritySource?: string;
  localEntityId?: string;
  /**
   * Set instead of `localEntityId` when this candidate comes from the
   * central database (syncToCentral) rather than this project's own PEDB.
   * Resolving it requires adopting a PEDB mirror first - see
   * `resolveCandidateForPedb`. When the project is synced, linked CEDB hits
   * are rewritten to carry `localEntityId` instead so accept/document checks
   * work without showing a Local vs Central split.
   */
  centralEntityId?: string;
  fromEntityFile?: boolean;
  /**
   * Years used by the Disambiguate date filter and (for places/offices / real floruit) captions.
   * For persons these may be birth/death, floruit earliest–latest, or CBDB index filter windows
   * — see {@link dateSource}. Index years are never minted or shown as `fl.`
   */
  startYear?: number;
  /** Death/dissolution year, or end of a floruit/filter/period interval. */
  endYear?: number;
  /**
   * Pack `metadata.dateSource`. `floruit` = real fl. earliest/latest; `index`/`nationality`
   * = filter anchors only (never shown/stored as floruit).
   */
  dateSource?: 'fine' | 'floruit' | 'index' | 'nationality';
  /** DILA place records are split one-per-dynasty (e.g. 東晉); kept for a future dynasty filter/picker. */
  dynasty?: string;
  /** Entity's full name in the project source language script (authority-provided). */
  projectLangName?: string;
  /** Latin-script name: authority-provided (pinyin/yomi/en label) or autogenerated. */
  romanizedName?: string;
  /** Typed names from the authority (courtesy/posthumous/…), ingested into entities.xml on linking. */
  typedNames?: TypedName[];
  /** WGS84 coordinates, when the source authority carries them (CHGIS, CBDB places). */
  geo?: { lat: number; lon: number };
  /** Raw pack metadata needed when the selected office is minted. */
  authorityMetadata?: AuthorityCandidate['metadata'];
  /** Raw authority rows retained when a display candidate is deduplicated. */
  authorityAssertions?: DisambiguationCandidate[];
}

/** Accept only WGS84 coordinates; CHGIS also contains projected layer values. */
export function normalizeGeo(
  geo: { lat: number; lon: number } | undefined,
): { lat: number; lon: number } | undefined {
  if (!geo || !Number.isFinite(geo.lat) || !Number.isFinite(geo.lon)) return undefined;
  if (geo.lat < -90 || geo.lat > 90 || geo.lon < -180 || geo.lon > 180) return undefined;
  return geo;
}

export interface TypedName {
  text: string;
  type: NameTypeId;
  lang?: string;
}

/** TEI tag → entity-lookup type (Attributes panel, disambiguation, packs). */
export const TAG_TO_ENTITY_TYPE: Record<string, NamedEntityType> = {
  persName: 'person',
  placeName: 'place',
  orgName: 'organization',
  org: 'organization',
  title: 'work',
  bibl: 'work',
  roleName: 'office',
  name: 'person',
};

const AUTHORITY_MAP: Record<
  string,
  'wikidata' | 'viaf' | 'dbpedia' | 'geonames' | 'getty' | 'gnd'
> = {
  Wikidata: 'wikidata',
  VIAF: 'viaf',
  DBPedia: 'dbpedia',
  Geonames: 'geonames',
  Getty: 'getty',
  GND: 'gnd',
};

/** Direct name children of an entity element (skips names nested in notes). */
function entityNameElements(element: Element, nameTag: string): Element[] {
  return Array.from(element.children).filter((child) => child.localName === nameTag);
}

/**
 * Match against any name child's text — `element.textContent` would also pick
 * up note/idno text. All name elements count, so a stored alternative name
 * (romanization, courtesy name, prior surface form) also finds the entity.
 */
function entityNameMatches(element: Element, nameTag: string, surface: string): boolean {
  return entityNameElements(element, nameTag).some((el) =>
    stringsMatchExactly(surface, textWithoutHiddenReadings(el).trim()),
  );
}

/** Pull a Wikidata Q-id from URIs, VIAF source codes (WKP|Q…), or free text. */
export function extractWikidataId(text: string): string | null {
  const urlMatch = text.match(/wikidata\.org\/(?:wiki|entity)\/(Q\d+)/i);
  if (urlMatch) return urlMatch[1]!.toUpperCase();

  const wkpMatch = text.match(/WKP\|(Q\d+)/i);
  if (wkpMatch) return wkpMatch[1]!.toUpperCase();

  const bare = text.match(/\b(Q\d{3,})\b/i);
  return bare ? bare[1]!.toUpperCase() : null;
}

/** Pull a VIAF numeric id from a cluster URI (with or without a locale segment, e.g. `viaf.org/fr/viaf/…`). */
export function extractViafId(text: string): string | null {
  const match = text.match(/viaf\.org\/(?:[a-z]{2}\/)?viaf\/(\d+)/i);
  return match ? match[1]! : null;
}

/** Pull a CBDB person id from LINCS/Wikidata description text (e.g. "CBDB ID = 392870"). */
export function extractCbdbId(text: string): string | null {
  const match = text.match(/CBDB\s*(?:ID\s*)?=\s*(\d+)/i);
  return match ? match[1]! : null;
}

export const CBDB_PERSON_URL = (id: string) =>
  `https://cbdb.fas.harvard.edu/cbdbapi/person.php?id=${id}`;
export const DILA_PERSON_URL = (id: string) =>
  `https://authority.dila.edu.tw/person/?fromInner=${id}`;
export const DILA_PLACE_URL = (id: string) =>
  `https://authority.dila.edu.tw/place/?fromInner=${id}`;
export const DILA_URL = (id: string) =>
  id.startsWith('PL') ? DILA_PLACE_URL(id) : DILA_PERSON_URL(id);

export type WikipediaSite = 'enwiki' | 'zhwiki';

export const WIKIDATA_ITEM_URL = (qid: string) => `https://www.wikidata.org/wiki/${qid}`;

/**
 * Open the Wikipedia article for a Q-id via Wikidata sitelinks.
 * Must use wikidata.org — `Special:EntityPage` is not a valid page on en.wikipedia.org.
 */
export const WIKIPEDIA_ARTICLE_URL = (qid: string, site: WikipediaSite = 'enwiki') =>
  `https://www.wikidata.org/wiki/Special:GoToLinkedPage/${site}/${qid}`;

export function preferredWikipediaSite(locale?: string): WikipediaSite {
  const primary = locale?.split('-')[0]?.toLowerCase();
  return primary === 'zh' ? 'zhwiki' : 'enwiki';
}

export interface CandidateLink {
  kind: 'wikidata' | 'viaf' | 'cbdb' | 'dila' | 'bdrc';
  url: string;
  title: string;
}

export interface CandidateLinkOptions {
  /** @deprecated Wikipedia sitelinks are not used; links open the Wikidata item page. */
  wikiSite?: WikipediaSite;
}

/** External links for a candidate row (Wikidata item, VIAF cluster, etc.). */
export function candidateLinks(
  candidate: DisambiguationCandidate,
  _options: CandidateLinkOptions = {},
): CandidateLink[] {
  const links: CandidateLink[] = [];
  const seen = new Set<string>();

  const add = (kind: CandidateLink['kind'], url: string, title: string) => {
    if (seen.has(url)) return;
    seen.add(url);
    links.push({ kind, url, title });
  };

  const scan = (text: string | undefined) => {
    if (!text) return;
    const qid = extractWikidataId(text);
    if (qid) {
      add('wikidata', WIKIDATA_ITEM_URL(qid), `Wikidata (${qid})`);
    }
    const viaf = extractViafId(text);
    if (viaf) add('viaf', `https://viaf.org/viaf/${viaf}`, `VIAF ${viaf}`);
    const cbdb = extractCbdbId(text);
    if (cbdb) add('cbdb', CBDB_PERSON_URL(cbdb), `CBDB ${cbdb}`);
    const bdrc = extractBdrcId(text);
    if (bdrc) add('bdrc', BDRC_SHOW_URL(bdrc), `BDRC ${bdrc}`);
  };

  scan(candidate.uri);
  scan(candidate.description);
  for (const auth of candidate.authorityIds ?? []) {
    if (auth.type === 'CBDB') {
      add('cbdb', CBDB_PERSON_URL(auth.value), `CBDB ${auth.value}`);
    }
    if (auth.type === 'DILA') {
      add('dila', DILA_URL(auth.value), `DILA ${auth.value}`);
    }
    if (auth.type.toLowerCase() === 'bdrc') {
      const bdrc = normalizeBdrcId(auth.value);
      if (bdrc) add('bdrc', BDRC_SHOW_URL(bdrc), `BDRC ${bdrc}`);
    }
    scan(auth.value);
  }

  return links;
}

/** Project-script name when we have one; otherwise the authority's own label. */
export function candidatePrimaryLabel(candidate: DisambiguationCandidate): string {
  const script = candidate.projectLangName?.trim();
  if (script && !isLatinSurface(script)) return script;
  return candidate.label;
}

/**
 * Transliteration on its own line only when the row has no description and no
 * dates — those already occupy the subtitle. Used so Tibetan Wylie sits under
 * the uchen label instead of competing as a second primary.
 */
export function candidateRomanizationSubtitle(
  candidate: DisambiguationCandidate,
): string | undefined {
  if (candidate.description?.trim()) return undefined;
  if (candidate.startYear != null || candidate.endYear != null) return undefined;
  const romanized = candidate.romanizedName?.trim();
  if (!romanized) return undefined;
  if (romanized === candidatePrimaryLabel(candidate)) return undefined;
  return romanized;
}

function authorityKeysForCandidate(candidate: DisambiguationCandidate): string[] {
  const keys = new Set<string>();
  const scan = (text: string | undefined) => {
    if (!text) return;
    const wd = normalizeWikidataQid(text) ?? extractWikidataId(text);
    if (wd) keys.add(`wikidata:${wd}`);
    const viaf = normalizeViafId(text) ?? extractViafId(text);
    if (viaf) keys.add(`viaf:${viaf}`);
    const cbdb = extractCbdbId(text);
    if (cbdb) keys.add(`cbdb:${cbdb}`);
    const bdrc = extractBdrcId(text);
    if (bdrc) keys.add(`bdrc:${bdrc}`);
  };

  scan(candidate.uri);
  scan(candidate.description);
  scan(candidate.label);
  for (const auth of candidate.authorityIds ?? []) {
    scan(auth.value);
    const type = auth.type.trim().toLowerCase();
    const value = auth.value.trim();
    if (!value) continue;
    if (type.includes('wikidata')) {
      const wd = normalizeWikidataQid(auth.value) ?? extractWikidataId(auth.value);
      if (wd) keys.add(`wikidata:${wd}`);
    }
    if (type === 'viaf') {
      const viaf = normalizeViafId(auth.value) ?? extractViafId(auth.value);
      if (viaf) keys.add(`viaf:${viaf}`);
    }
    // Case-insensitive so PEDB idnos (NORBERT/CBDB) collapse with pack rows.
    if (type === 'cbdb') keys.add(`cbdb:${value}`);
    if (type === 'dila') keys.add(`dila:${value}`);
    if (type === 'bdrc') {
      const bdrc = normalizeBdrcId(value);
      if (bdrc) keys.add(`bdrc:${bdrc}`);
    }
    if (type === 'norbert') {
      keys.add(`norbert:${value}`);
      // Typed (`office-4135`) and bare (`4135`) forms must collapse for the
      // same kind during the migration window.
      const kindPrefixed = value.match(/^(person|office|place)[-:](.+)$/i);
      if (kindPrefixed) {
        keys.add(`norbert:${kindPrefixed[2]}`);
        keys.add(`norbert:${kindPrefixed[1]!.toLowerCase()}-${kindPrefixed[2]}`);
      }
    }
  }
  return [...keys];
}

function dedupeAuthorityIds(ids: AuthorityId[]): AuthorityId[] {
  const seen = new Set<string>();
  return ids.filter((id) => {
    const key = `${id.type}\0${id.value}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

/** Pull cross-authority ids embedded in reconcile description text. */
export function enrichCandidateCrossRefs(
  candidate: DisambiguationCandidate,
): DisambiguationCandidate {
  const authorityIds = dedupeAuthorityIds(
    authorityIdsFromCrossRefs(candidate.authorityIds ?? [], candidate.description, candidate.uri),
  );
  return { ...candidate, authorityIds };
}

function authorityIdsFromCrossRefs(
  base: AuthorityId[],
  ...texts: (string | undefined)[]
): AuthorityId[] {
  const out = [...base];
  const seen = new Set(out.map((id) => `${id.type}\0${id.value}`));
  const add = (type: AuthorityId['type'], value: string) => {
    const key = `${type}\0${value}`;
    if (seen.has(key)) return;
    seen.add(key);
    out.push({ type, value });
  };
  for (const text of texts) {
    if (!text) continue;
    const wikidata = text.match(/wikidata\.org\/(?:wiki|entity)\/(Q\d+)/i)?.[1]?.toUpperCase();
    if (wikidata) add('Wikidata', wikidata);

    const viaf = text.match(/viaf\.org\/(?:[a-z]{2}\/)?viaf\/(\d+)/i)?.[1];
    if (viaf) add('VIAF', viaf);

    const cbdb = extractCbdbId(text);
    if (cbdb) add('CBDB', cbdb);

    const dila = text.match(
      /authority\.dila\.edu\.tw\/[^\s]*?(?:aid=|fromInner=|code=|\/)([A-Z]{1,2}\d+)/,
    )?.[1];
    if (dila) add('DILA', dila);

    const ndl = text.match(/id\.ndl\.go\.jp\/auth\/(?:ndlna|ndlsh)\/([\w-]+)/i)?.[1];
    if (ndl) add('NDL', ndl);

    const bdrc = extractBdrcId(text);
    if (bdrc) add('BDRC', bdrc);
  }
  return out;
}

export interface MergeCandidateOptions {
  /**
   * Deterministic label for non-Latin projects: prefer a project-script label
   * over whichever row happens to come first (pack rows can surface a
   * romanized or Korean label for a Chinese person, depending on which
   * search string matched).
   */
  preferNonLatinLabel?: boolean;
  /** The mention group's tag — geo-cluster merging only applies to `'placeName'`. */
  tag?: string;
  /**
   * Radius (km) within which two place candidates are treated as the same
   * functional location and collapsed into one row (see
   * docs/placename-geo-disambiguation-planning.md, Phase 6). Only takes
   * effect when `tag === 'placeName'`.
   */
  placeProximityKm?: number;
}

/** Merge checked rows into one candidate (manual link or accept). */
export function mergeSelectedCandidates(
  candidates: DisambiguationCandidate[],
  options?: MergeCandidateOptions,
): DisambiguationCandidate | null {
  if (candidates.length === 0) return null;
  const first = candidates[0]!;
  const fromFile = candidates.find((c) => c.fromEntityFile);
  const projectLangName = candidates.map((c) => c.projectLangName).find(Boolean);
  const romanizedName = candidates.map((c) => c.romanizedName).find(Boolean);
  const typedByText = new Map<string, TypedName>();
  for (const candidate of candidates) {
    for (const name of candidate.typedNames ?? []) {
      const key = name.text.normalize('NFC');
      if (!typedByText.has(key)) typedByText.set(key, name);
    }
  }
  const normalizedTypedNames = normalizeTypedNamesForIntake([...typedByText.values()]);
  const typedNames = normalizedTypedNames.length ? normalizedTypedNames : undefined;
  const nonLatinLabel = options?.preferNonLatinLabel
    ? (candidates.map((c) => c.label).find((label) => label && !isLatinSurface(label)) ??
      candidates.map((c) => c.projectLangName).find((name) => name && !isLatinSurface(name)) ??
      projectLangName)
    : undefined;
  const authorityAssertionMap = new Map<string, DisambiguationCandidate>();
  for (const candidate of candidates.flatMap((candidate) => {
    if (candidate.authorityAssertions?.length) return candidate.authorityAssertions;
    if (candidate.fromEntityFile || candidate.localEntityId || candidate.centralEntityId) return [];
    return [candidate];
  })) {
    const key = `${candidate.uri ?? candidate.id}\0${candidate.sources.join(',')}`;
    authorityAssertionMap.set(key, candidate);
  }
  const authorityAssertions = [...authorityAssertionMap.values()];
  const bioBearing = candidates.filter(
    (c) => !isFilterOnlyDateSource(c.dateSource) && (c.startYear != null || c.endYear != null),
  );
  const yearSources = bioBearing.length ? bioBearing : candidates;
  const startYears = yearSources.map((c) => c.startYear).filter((y): y is number => y != null);
  const endYears = yearSources.map((c) => c.endYear).filter((y): y is number => y != null);
  const filterOnly = candidates.find((c) => isFilterOnlyDateSource(c.dateSource));
  const dateSource = bioBearing.length
    ? (bioBearing.find((c) => c.dateSource === 'fine')?.dateSource ?? undefined)
    : filterOnly?.dateSource;
  return {
    id: fromFile?.id ?? first.id,
    label: fromFile?.label ?? nonLatinLabel ?? first.label,
    projectLangName,
    romanizedName,
    typedNames,
    description:
      [...new Set(candidates.map((c) => c.description).filter(Boolean))].join(' · ') ||
      first.description,
    sources: [...new Set(candidates.flatMap((c) => c.sources))],
    uri: fromFile?.uri ?? first.uri,
    localEntityId: fromFile?.localEntityId ?? first.localEntityId,
    centralEntityId: fromFile?.centralEntityId ?? first.centralEntityId,
    fromEntityFile: candidates.some((c) => c.fromEntityFile),
    authorityIds: dedupeAuthorityIds(candidates.flatMap((c) => c.authorityIds ?? [])),
    startYear: startYears.length ? Math.min(...startYears) : undefined,
    endYear: endYears.length ? Math.max(...endYears) : undefined,
    dateSource,
    dynasty: candidates.find((c) => c.dynasty)?.dynasty,
    geo: mergedGeo(candidates),
    authorityMetadata:
      candidates.find((c) => c.authorityMetadata)?.authorityMetadata ?? first.authorityMetadata,
    authorityAssertions: authorityAssertions.length ? authorityAssertions : undefined,
  };
}

/**
 * Representative point for a merged row: the centroid of every source
 * candidate that carries coordinates. A single geo-bearing candidate's
 * centroid is just that point, so this subsumes the old first-wins
 * behavior for non-place merges while giving places (Phase 6) the "mean of
 * the cluster" point the disambiguation-panel map needs.
 */
function mergedGeo(
  candidates: DisambiguationCandidate[],
): { lat: number; lon: number } | undefined {
  const points = candidates
    .map((c) => c.geo)
    .filter((geo): geo is { lat: number; lon: number } => geo != null);
  return points.length > 0 ? centroidOf(points) : undefined;
}

/** Collapse rows that share a Wikidata Q-id or other cross-authority key. */
export function collapseCrossAuthorityCandidates(
  candidates: DisambiguationCandidate[],
  options?: MergeCandidateOptions,
): DisambiguationCandidate[] {
  if (candidates.length < 2) return candidates;

  const parent = candidates.map((_, index) => index);
  const find = (index: number): number =>
    parent[index] === index ? index : (parent[index] = find(parent[index]!));
  const union = (a: number, b: number) => {
    parent[find(a)] = find(b);
  };

  const keyToIndices = new Map<string, number[]>();
  candidates.forEach((candidate, index) => {
    for (const key of authorityKeysForCandidate(candidate)) {
      const list = keyToIndices.get(key) ?? [];
      list.push(index);
      keyToIndices.set(key, list);
    }
  });

  for (const indices of keyToIndices.values()) {
    const head = indices[0]!;
    for (let i = 1; i < indices.length; i++) union(head, indices[i]!);
  }

  // Different authorities agreeing on the exact same birth and death years is
  // itself a strong enough signal to treat two rows as the same person, even
  // without a shared cross-referenced id.
  for (let i = 0; i < candidates.length; i++) {
    for (let j = i + 1; j < candidates.length; j++) {
      if (find(i) === find(j)) continue;
      const a = candidates[i]!;
      const b = candidates[j]!;
      const sameAuthority = a.sources.some((source) => b.sources.includes(source));
      if (sameAuthority) continue;
      if (a.startYear == null || a.endYear == null) continue;
      if (a.startYear !== b.startYear || a.endYear !== b.endYear) continue;
      union(i, j);
    }
  }

  // Place candidates within the configured proximity radius are treated as
  // the same functional location (docs/placename-geo-disambiguation-planning.md,
  // Phase 6) — same union-find, so it composes with the id/year passes above
  // rather than replacing them. Candidates missing coordinates never merge on
  // this pass (mirrors authorityOverlap.ts's shouldMergePlacePackCandidates).
  if (options?.tag === 'placeName' && options?.placeProximityKm != null) {
    for (let i = 0; i < candidates.length; i++) {
      for (let j = i + 1; j < candidates.length; j++) {
        if (find(i) === find(j)) continue;
        const a = candidates[i]!;
        const b = candidates[j]!;
        if (!a.geo || !b.geo) continue;
        if (haversineDistanceKm(a.geo, b.geo) > options.placeProximityKm) continue;
        union(i, j);
      }
    }
  }

  const groups = new Map<number, DisambiguationCandidate[]>();
  candidates.forEach((candidate, index) => {
    const root = find(index);
    const list = groups.get(root) ?? [];
    list.push(candidate);
    groups.set(root, list);
  });

  return [...groups.values()].map((group) => mergeSelectedCandidates(group, options)!);
}

/** Candidates from the local entity file matching surface text. */
export function candidatesFromEntityFile(
  doc: Document,
  tag: string,
  surface: string,
  origin: 'pedb' | 'cedb' = 'pedb',
): DisambiguationCandidate[] {
  const kind = tag === 'name' ? 'person' : TAG_TO_KIND[tag];
  if (!kind) return [];

  const nameTag = ENTITY_KINDS[kind].name;
  const items = entityElements(doc, kind);
  const out: DisambiguationCandidate[] = [];
  for (let i = 0; i < items.length; i++) {
    const el = items[i]!;
    if (!entityNameMatches(el, nameTag, surface)) continue;
    const localId = el.getAttribute('xml:id') ?? '';
    const idnos = Array.from(el.getElementsByTagName('idno'));
    const authorityIds: AuthorityId[] = idnos.map((idno) => ({
      type: idno.getAttribute('type') ?? 'unknown',
      value: idno.textContent?.trim() ?? '',
    }));
    const notes = Array.from(el.getElementsByTagName('note'));
    const descriptionNote =
      notes.find((note) => note.getAttribute('type') === 'description') ??
      notes.find((note) => !note.getAttribute('type'));
    let startYear =
      parseIsoYear(el.getElementsByTagName('birth')[0]?.getAttribute('when')) ?? undefined;
    let endYear =
      parseIsoYear(el.getElementsByTagName('death')[0]?.getAttribute('when')) ?? undefined;
    const datesNote = notes.find((note) => note.getAttribute('type') === 'dates');
    if (startYear == null && endYear == null && datesNote) {
      const [start, end] = (datesNote.textContent ?? '').split('/');
      startYear = parseIsoYear(start) ?? undefined;
      endYear = parseIsoYear(end) ?? undefined;
    }
    const nameEls = entityNameElements(el, nameTag);
    const nameTexts = nameEls.map((name) => textWithoutHiddenReadings(name).trim()).filter(Boolean);
    const romanizedNameEl = nameEls.find((name) => isLatnLang(name.getAttribute('xml:lang')));
    const romanizedName = romanizedNameEl
      ? textWithoutHiddenReadings(romanizedNameEl).trim()
      : undefined;
    out.push({
      id: localId || `local-${i}`,
      label: nameTexts[0] || surface,
      description: descriptionNote?.textContent ?? undefined,
      sources: origin === 'cedb' ? ['central-database'] : ['entity-file'],
      localEntityId: origin === 'pedb' ? localId || undefined : undefined,
      centralEntityId: origin === 'cedb' ? localId || undefined : undefined,
      authorityIds,
      fromEntityFile: true,
      startYear,
      endYear,
      projectLangName: nameTexts.find((text) => !isLatinSurface(text)),
      romanizedName: romanizedName || undefined,
    });
  }
  return out;
}

/** Minimal entity snapshot for building disambiguation candidates from SQLite. */
export interface SqliteDisambiguationEntityInput {
  id: string;
  label: string;
  description?: string | null;
  authorities?: AuthorityId[];
  names: { text: string; language?: string | null }[];
  startYear?: number | null;
  endYear?: number | null;
}

/**
 * Same surface-matching behaviour as `candidatesFromEntityFile`, but from typed
 * SQLite rows (search + panel summary) instead of a full XML export.
 */
export function candidatesFromSqliteEntities(
  entities: readonly SqliteDisambiguationEntityInput[],
  surface: string,
  origin: 'pedb' | 'cedb' = 'pedb',
): DisambiguationCandidate[] {
  const out: DisambiguationCandidate[] = [];
  for (const entity of entities) {
    const nameTexts = entity.names.map((name) => name.text.trim()).filter(Boolean);
    if (!nameTexts.some((text) => stringsMatchExactly(surface, text))) continue;
    const romanizedName = entity.names
      .find((name) => isLatnLang(name.language ?? null))
      ?.text.trim();
    out.push({
      id: entity.id,
      label: entity.label || nameTexts[0] || surface,
      description: entity.description ?? undefined,
      sources: origin === 'cedb' ? ['central-database'] : ['entity-file'],
      localEntityId: origin === 'pedb' ? entity.id : undefined,
      centralEntityId: origin === 'cedb' ? entity.id : undefined,
      authorityIds: entity.authorities ?? [],
      fromEntityFile: true,
      startYear: entity.startYear ?? undefined,
      endYear: entity.endYear ?? undefined,
      projectLangName: nameTexts.find((text) => !isLatinSurface(text)),
      romanizedName: romanizedName || undefined,
    });
  }
  return out;
}

/** Provenance keys that mean "from this user's entity database" (PEDB or CEDB). */
const OWN_DATABASE_SOURCES = new Set(['entity-file', 'central-database', 'pedb', 'cedb']);

export function isOwnDatabaseSource(source: string): boolean {
  return OWN_DATABASE_SOURCES.has(source.trim().toLowerCase());
}

/** Drop Local/Central provenance labels so synced projects do not show that split. */
export function stripOwnDatabaseSources(sources: string[]): string[] {
  return sources.filter((source) => !isOwnDatabaseSource(source));
}

/**
 * Rewrite an entity-database candidate for a syncToCentral project: strip
 * Local/Central source labels, and when a PEDB mirror id is known prefer that
 * so "already in document" / accept paths use the project key.
 */
export function asSyncedEntityCandidate(
  candidate: DisambiguationCandidate,
  linkedPedbId?: string | null,
): DisambiguationCandidate {
  const pedbId = linkedPedbId?.trim() || undefined;
  return {
    ...candidate,
    sources: stripOwnDatabaseSources(candidate.sources),
    localEntityId: pedbId ?? candidate.localEntityId,
    centralEntityId: pedbId ? undefined : candidate.centralEntityId,
  };
}

/** How many same-surface PEDB/CEDB hits disambiguation will load from SQLite. */
const SQLITE_DISAMBIGUATION_SEARCH_LIMIT = 200;

/**
 * Load surface-matching disambiguation candidates from a migrated SQLite store.
 * Returns null when SQLite search is unavailable — callers must fail loud,
 * not fall back to XML/`loadEntities`.
 */
export async function loadSqliteDisambiguationCandidates(
  store: EntityStore,
  tag: string,
  surface: string,
  origin: 'pedb' | 'cedb' = 'pedb',
): Promise<DisambiguationCandidate[] | null> {
  const kind = tag === 'name' ? 'person' : TAG_TO_KIND[tag];
  if (!kind) return [];
  const hits = await store.sqliteSearchNames(kind, surface, SQLITE_DISAMBIGUATION_SEARCH_LIMIT);
  if (hits == null) return null;

  const entities: SqliteDisambiguationEntityInput[] = [];
  for (const hit of hits) {
    const summary = (await store.sqliteEntitySummary(hit.id)) as {
      id?: string;
      description?: string | null;
      authorities?: AuthorityId[];
      names?: { text: string; language?: string | null; status?: string }[];
      startYear?: number | null;
      endYear?: number | null;
    } | null;
    if (!summary) continue;
    const names = (summary.names ?? [])
      .filter((name) => name.status !== 'rejected' && name.status !== 'withdrawn')
      .map((name) => ({ text: name.text, language: name.language ?? null }));
    entities.push({
      id: summary.id ?? hit.id,
      label: hit.label,
      description: summary.description ?? hit.description ?? null,
      authorities: summary.authorities ?? hit.idnos,
      names: names.length > 0 ? names : [{ text: hit.label, language: null }],
      startYear: summary.startYear ?? null,
      endYear: summary.endYear ?? null,
    });
  }
  return candidatesFromSqliteEntities(entities, surface, origin);
}

function mergeIntoExisting(
  existing: DisambiguationCandidate,
  candidate: DisambiguationCandidate,
): void {
  existing.sources = Array.from(new Set([...existing.sources, ...candidate.sources]));
  if (candidate.authorityIds) {
    existing.authorityIds = [...(existing.authorityIds ?? []), ...candidate.authorityIds];
  }
  existing.geo ??= candidate.geo;
}

export function mergeCandidates(
  lists: DisambiguationCandidate[][],
  options?: MergeCandidateOptions,
): DisambiguationCandidate[] {
  const byLocal = new Map<string, DisambiguationCandidate>();
  const byCentral = new Map<string, DisambiguationCandidate>();
  const out: DisambiguationCandidate[] = [];

  for (const list of lists) {
    for (const candidate of list.flatMap((item) =>
      item.authorityAssertions?.length ? [item, ...item.authorityAssertions] : [item],
    )) {
      if (candidate.localEntityId) {
        const existing = byLocal.get(candidate.localEntityId);
        if (existing) {
          mergeIntoExisting(existing, candidate);
          continue;
        }
        byLocal.set(candidate.localEntityId, candidate);
        out.push(candidate);
        continue;
      }

      if (candidate.centralEntityId) {
        const existing = byCentral.get(candidate.centralEntityId);
        if (existing) {
          mergeIntoExisting(existing, candidate);
          continue;
        }
        byCentral.set(candidate.centralEntityId, candidate);
        out.push(candidate);
        continue;
      }

      const dup = out.find((c) => c.uri && c.uri === candidate.uri);
      if (dup) {
        mergeIntoExisting(dup, candidate);
        continue;
      }
      out.push(candidate);
    }
  }
  return collapseCrossAuthorityCandidates(out.map(enrichCandidateCrossRefs), options);
}

/** Session-lifetime cache of Wikidata Q-id → lifespan (or null when none found). */
const wikidataLifespanCache = new Map<string, Awaited<ReturnType<typeof fetchWikidataLifespan>>>();

/** Drop Wikidata reconcile rows whose Q-id is not the expected entity kind. */
async function filterWikidataByKind<T extends { uri: string; description?: string }>(
  matches: T[],
  kind: EntityKind,
  cache: AuthorityCache,
): Promise<T[]> {
  if (matches.length === 0) return matches;

  const withQid: { match: T; qid: string }[] = [];
  for (const match of matches) {
    const qid = extractWikidataId(match.uri) ?? extractWikidataId(match.description ?? '');
    if (qid) withQid.push({ match, qid });
  }
  if (withQid.length === 0) return [];

  const qids = [...new Set(withQid.map((row) => row.qid))];
  await cache.throttle();
  const matching = await wikidataQidsMatchingKind(qids, kind);
  return withQid.filter((row) => matching.has(row.qid)).map((row) => row.match);
}

export type ReadAuthorityPackFile = (packId: AuthorityPackId) => Promise<AuthorityPackContent>;

export function clearPersonPackIndexForTests(): void {
  chgisIndexPromise = null;
}

/** Session-lifetime cache of parsed CHGIS rows, keyed by exact search string. */
let chgisIndexPromise: Promise<Map<string, { startYear?: number; endYear?: number }>> | null = null;

function buildChgisIndex(
  rows: AuthorityCandidate[],
): Map<string, { startYear?: number; endYear?: number }> {
  const index = new Map<string, { startYear?: number; endYear?: number }>();
  for (const row of rows) {
    const years = { startYear: row.metadata?.startYear, endYear: row.metadata?.endYear };
    if (years.startYear == null && years.endYear == null) continue;
    for (const str of row.searchStrings) {
      if (!index.has(str)) index.set(str, years);
    }
  }
  return index;
}

/** Look up begin/end years for a place surface string in the installed CHGIS pack (cached for the session). */
async function chgisYearsForSurface(
  surface: string,
  readPackFile: ReadAuthorityPackFile,
): Promise<{ startYear?: number; endYear?: number } | null> {
  chgisIndexPromise ??= (async () => {
    try {
      const content = await readPackFile('chgis-places');
      return buildChgisIndex(parseAuthorityNdjson(content));
    } catch {
      return new Map();
    }
  })();
  const index = await chgisIndexPromise;
  return index.get(surface) ?? null;
}

/**
 * Fetch and cache live 備註/朝代 dates for a DILA place id in the background.
 * Local pack metadata already covers a handful of places whose remark date range
 * was extractable from the bulk XML export; this fills in the rest on demand,
 * scraping the live record page (there is no by-string search API — only by id).
 * Fire-and-forget: the disambiguation panel must not block on a live network
 * scrape just to open, so misses are queued rather than awaited inline.
 */
async function fetchAndCacheDilaPlaceDetail(
  authorityId: string,
  dilaDetailCache: DilaPlaceDetailCache,
  fetchImpl?: DilaFetchFn,
): Promise<void> {
  await dilaDetailCache.throttle();
  try {
    const detail = await fetchDilaPlaceDetail(authorityId, fetchImpl);
    if (detail) await dilaDetailCache.set(authorityId, detail);
  } catch {
    // best-effort; the candidate stays undated until a later lookup retries
  }
}

async function candidatesFromAuthorityPacks(
  tag: string,
  surface: string,
  readPackFile: ReadAuthorityPackFile,
  dilaDetailCache?: DilaPlaceDetailCache,
  dilaFetchImpl?: DilaFetchFn,
  onDilaDatesReady?: () => void,
  projectLang?: string | null,
): Promise<DisambiguationCandidate[]> {
  const entityType = TAG_TO_ENTITY_TYPE[tag] ?? 'person';
  const packIds = packIdsForEntityType(
    [
      'cbdb-persons',
      'cbdb-places',
      'cbdb-offices',
      'dila-persons',
      'dila-places',
      'chgis-places',
      'ndl-persons',
      'ndl-places',
      'ndl-orgs',
      'ndl-works',
      'norbert-persons',
      'norbert-person-wrappers',
      'norbert-wiki-nt',
      'norbert-offices',
    ],
    entityType,
  );
  const pendingDilaFetches: Promise<void>[] = [];
  const officeGlosses =
    entityType === 'office' ? await loadHuckbotGlossIndex(readPackFile) : undefined;
  const frenchOfficeGlosses =
    entityType === 'office' ? await loadMaxiRicciGlossIndex(readPackFile) : undefined;
  // Read packs in parallel — sequential awaits made lookup feel much slower
  // than the legacy per-authority popup (which also fired searches together).
  const perPack = await Promise.all(
    packIds.map(async (packId): Promise<DisambiguationCandidate[]> => {
      try {
        const content = await readPackFile(packId);
        const spec = AUTHORITY_PACKS.find((item) => item.id === packId);
        if (!spec) return [];
        const packSource = spec.source as 'cbdb' | 'dila' | 'chgis' | 'ndl' | 'norbert';
        const results: DisambiguationCandidate[] = [];
        // searchPackRows hands back each match's parsed ndjson row, so the
        // metadata (years, dynasty, authorityId) comes straight from the ≤10
        // matched lines — no full-pack parse per lookup.
        for (const { result: match, row } of searchPackRows(
          content,
          packSource,
          entityType,
          surface,
          undefined,
          officeGlosses,
          frenchOfficeGlosses,
        )) {
          let description = match.description;
          let dateSource = row?.metadata?.dateSource;
          if (entityType === 'person' && dateSource === 'index') {
            description = scrubIndexYearFloruitClue(description);
          }
          const filterYears =
            entityType === 'person'
              ? filterYearsFromMetadata(row?.metadata)
              : {
                  startYear: row?.metadata?.startYear ?? undefined,
                  endYear: row?.metadata?.endYear ?? undefined,
                  isFine: true,
                };
          let startYear = filterYears.startYear;
          let endYear = filterYears.endYear;
          let dynasty: string | undefined;

          // A dynasty span is not a lifespan. When the years were computed from one,
          // label them `nationality` whatever the pack claimed: the Norbert person
          // pack sets no `dateSource` on any of its 16,050 rows, so trusting that
          // field let dynasty ranges reach birth/death and show on the disambiguation
          // panel as the person's own dates. With the label applied,
          // `isFilterOnlyDateSource` keeps them out of vitals and the authority
          // backfill can strip the ones earlier mints already stored.
          if (filterYears.derivedFromDynasty) dateSource = 'nationality';

          if (
            packSource === 'dila' &&
            entityType === 'place' &&
            dilaDetailCache &&
            row?.authorityId &&
            startYear == null &&
            endYear == null
          ) {
            const cached = await dilaDetailCache.get(row.authorityId);
            if (cached) {
              startYear = cached.startYear ?? startYear;
              endYear = cached.endYear ?? endYear;
              if (cached.remark) description = cached.remark;
              // DILA splits a place into one record per dynasty — lead with it so
              // same-named candidates read as distinct entries, and keep it on the
              // candidate/cache for a future dynasty filter/picker.
              if (cached.dynasty) {
                dynasty = cached.dynasty;
                description = description ? `${cached.dynasty}：${description}` : cached.dynasty;
              }
            } else {
              // Don't block opening the panel on a live scrape; queue it and
              // let the caller refresh once every queued id has resolved.
              pendingDilaFetches.push(
                fetchAndCacheDilaPlaceDetail(row.authorityId, dilaDetailCache, dilaFetchImpl),
              );
            }
          }

          results.push({
            id: match.uri,
            label: match.label,
            description,
            sources: [
              spec.source.toUpperCase(),
              ...(row?.metadata?.crosswalk?.bdrc ? ['BDRC'] : []),
            ],
            uri: match.uri,
            authorityIds: dedupeAuthorityIds(
              // The bare authorityId, not match.uri — auth.value must be an id a
              // *_URL() builder can format, not an already-fully-formed URL (which
              // would otherwise get wrapped inside another URL and break the link).
              // Norbert values are kind-prefixed (`office-4135`) so person/office
              // numeric ids cannot collide in the entity DB.
              // Pack crosswalk (incl. VIAF P214 / Wikidata Q) is first-class —
              // do not rely on scraping description text for those ids.
              authorityIdsFromCrossRefs(
                [
                  {
                    type: packSource.toUpperCase(),
                    value:
                      packSource === 'norbert' && row?.authorityId != null
                        ? formatNorbertAuthorityValue(entityType, row.authorityId)
                        : (row?.authorityId ?? match.uri),
                  },
                  ...authorityIdsFromPackCrosswalk(row?.metadata?.crosswalk, {
                    norbertKind: entityType,
                  }),
                ],
                match.description,
              ),
            ),
            startYear,
            endYear,
            dateSource:
              dateSource === 'fine' ||
              dateSource === 'floruit' ||
              dateSource === 'index' ||
              dateSource === 'nationality'
                ? dateSource
                : undefined,
            dynasty,
            projectLangName: (() => {
              const displayName = row?.displayName?.trim() || row?.primaryName;
              return displayName && !isLatinSurface(displayName) ? displayName : undefined;
            })(),
            romanizedName:
              romanizeFromAuthorityMetadata(
                row?.metadata,
                (row?.displayName?.trim() || row?.primaryName) ?? match.label,
                projectLang,
                entityType,
              ) ?? undefined,
            typedNames: typedNamesFromPackRow(row?.names),
            geo: normalizeGeo(row?.metadata?.geo),
            authorityMetadata: row?.metadata,
          });
        }
        return results;
      } catch {
        // Missing or unreadable pack; skip it.
        return [];
      }
    }),
  );
  if (pendingDilaFetches.length > 0 && onDilaDatesReady) {
    void Promise.all(pendingDilaFetches).then(onDilaDatesReady);
  }
  return perPack.flat();
}

/**
 * Same include/exclude semantics as {@link candidatePassesDateFilter}, applied to a live
 * disambiguation candidate's `startYear`/`endYear` (persons, and CHGIS-matched places).
 */
export function candidatePassesYearFilter(
  candidate: DisambiguationCandidate,
  filter?: DateRangeFilter,
): boolean {
  if (!filter || filter.mode === 'none') return true;

  const { start, end } = normalizeDateRangeFilter(filter);
  const yearStart = candidate.startYear;
  const yearEnd = candidate.endYear ?? candidate.startYear;
  const undated = yearStart == null && yearEnd == null;

  if (undated) return filter.mode === 'exclude';

  const lo = yearStart ?? yearEnd!;
  const hi = yearEnd ?? yearStart!;
  const overlaps =
    filter.mode === 'exclude'
      ? preciseDateExceedsExcludeLimit(yearStart, candidate.endYear, start)
      : lo <= end && hi >= start;
  return filter.mode === 'limit' ? overlaps : !overlaps;
}

async function lifespanForQid(qid: string, cache: AuthorityCache) {
  if (wikidataLifespanCache.has(qid)) return wikidataLifespanCache.get(qid)!;
  await cache.throttle();
  let lifespan: Awaited<ReturnType<typeof fetchWikidataLifespan>>;
  try {
    lifespan = await fetchWikidataLifespan(qid);
  } catch {
    lifespan = null;
  }
  wikidataLifespanCache.set(qid, lifespan);
  return lifespan;
}

export interface FetchLiveCandidatesOptions {
  /**
   * Fetch Wikidata birth/death years for each hit. Each call is throttled (~1s),
   * so enabling this for many QIDs is slow. Lookup dialogs should pass false;
   * the disambiguation panel keeps the default (true).
   */
  enrichLifespans?: boolean;
}

export async function fetchLiveCandidates(
  tag: string,
  surface: string,
  cache: AuthorityCache,
  enabledAuthorities: (keyof typeof AUTHORITY_MAP)[],
  forceRefresh = false,
  readPackFile?: ReadAuthorityPackFile,
  options: FetchLiveCandidatesOptions = {},
): Promise<DisambiguationCandidate[]> {
  const enrichLifespans = options.enrichLifespans !== false;
  const entityType = TAG_TO_ENTITY_TYPE[tag] ?? 'person';
  const entityKind = tag === 'name' ? 'person' : TAG_TO_KIND[tag];
  const chgisYears =
    tag === 'placeName' && readPackFile ? await chgisYearsForSurface(surface, readPackFile) : null;

  // Fire Wikidata + VIAF (etc.) together, like the legacy lookup popup.
  const perAuthority = await Promise.all(
    enabledAuthorities.map(async (name): Promise<DisambiguationCandidate[]> => {
      const authorityId = AUTHORITY_MAP[name];
      if (!authorityId) return [];

      const cached = await cache.get(name, entityType, surface, forceRefresh);
      let matches: AuthorityLookupResult[] = cached?.results ?? [];

      if (!cached) {
        await cache.throttle();
        try {
          matches = await reconcile({
            query: surface,
            entityType,
            options: { authorityId, isUserAuthenticated: false },
          });
          await cache.set({
            authority: name,
            entityType,
            query: surface,
            fetchedAt: new Date().toISOString(),
            results: matches,
          });
        } catch {
          matches = [];
        }
      }

      if (name === 'Wikidata') {
        if (entityKind) {
          matches = await filterWikidataByKind(matches, entityKind, cache);
        }
        // Exact-surface matching only makes sense against Wikidata: its reconcile rows
        // reliably return the queried script as label/alias. VIAF/DBpedia/Getty/GND
        // headings are authority-specific (often romanized, "Surname, Given, dates")
        // and rarely equal the raw surface text — filtering them the same way silently
        // dropped every non-Wikidata authority.
        matches = await filterReconcileByExactSurface(matches, surface);
      }

      const results: DisambiguationCandidate[] = [];
      for (const match of matches) {
        let description = match.description;
        let startYear: number | undefined;
        let endYear: number | undefined;
        if (enrichLifespans && entityType === 'person') {
          const qid = extractWikidataId(match.uri) ?? extractWikidataId(match.description ?? '');
          if (qid) {
            const lifespan = await lifespanForQid(qid, cache);
            description = prefixDescriptionWithLifespan(description, lifespan);
            startYear = lifespan?.birthYear;
            endYear = lifespan?.deathYear;
          }
        } else if (entityType === 'place' && chgisYears) {
          startYear = chgisYears.startYear;
          endYear = chgisYears.endYear;
        }
        results.push({
          id: match.uri,
          label: match.label,
          description,
          sources: [name],
          uri: match.uri,
          authorityIds: dedupeAuthorityIds(
            authorityIdsFromCrossRefs([{ type: name, value: match.uri }], match.description),
          ),
          startYear,
          endYear,
        });
      }
      return results;
    }),
  );

  return perAuthority.flat();
}

/**
 * Best-effort dual-script name fill. One Wikidata label batch plus, when needed,
 * a VIAF cluster fetch so native-script headings (`bo`, `zh`, `ja`, …) are not
 * dropped in favour of the Latin catalogue form LINCS returns. Mutates in place.
 */
export async function enrichCandidateNames(
  candidates: DisambiguationCandidate[],
  projectLang: string | null | undefined,
  fetchImpl?: WikidataFetchFn,
  kind?: EntityKind | null,
): Promise<void> {
  if (!projectLang) return;

  const needy = candidates.filter((c) => !c.projectLangName || !c.romanizedName);
  const qidsOf = (candidate: DisambiguationCandidate): string[] => [
    ...new Set([
      ...extractWikidataIdsFromText(candidate.uri),
      ...extractWikidataIdsFromText(candidate.description),
      ...(candidate.authorityIds ?? [])
        .filter((auth) => /^wikidata$/i.test(auth.type))
        .flatMap((auth) => extractWikidataIdsFromText(auth.value)),
    ]),
  ];

  let labelsByQid = new Map<string, Record<string, string>>();
  const allQids = [...new Set(needy.flatMap(qidsOf))];
  if (allQids.length > 0) {
    try {
      labelsByQid = await wikidataLabelsByQid(allQids, fetchImpl);
    } catch {
      // offline / API failure: fall through to VIAF / autogeneration
    }
  }

  const viafFetch: ViafFetchFn = (url, init) =>
    fetchImpl ? (fetchImpl as ViafFetchFn)(url, init) : fetch(url, init);
  const viafIds = [
    ...new Set(
      needy
        .filter((candidate) => !candidate.projectLangName)
        .flatMap((candidate) => viafIdsOnCandidate(candidate)),
    ),
  ];
  const viafNativeById = new Map<string, string | null>();
  if (viafIds.length > 0) {
    await Promise.all(
      viafIds.map(async (id) => {
        const heading = await viafNativeHeadingForId(id, projectLang, viafFetch);
        viafNativeById.set(id, heading);
      }),
    );
  }

  for (const candidate of needy) {
    const originalLabel = candidate.label;
    const labels: Record<string, string> = {};
    for (const qid of qidsOf(candidate)) Object.assign(labels, labelsByQid.get(qid) ?? {});

    const viafNative = viafIdsOnCandidate(candidate)
      .map((id) => viafNativeById.get(id))
      .find((heading): heading is string => Boolean(heading));

    candidate.projectLangName ??=
      preferredLabelForLang(labels, projectLang) ??
      viafNative ??
      (!isLatinSurface(candidate.label) ? candidate.label : undefined);

    if (!candidate.romanizedName) {
      const scriptName = candidate.projectLangName ?? candidate.label;
      const generated = autoRomanizeForKind(scriptName, projectLang, kind) ?? undefined;
      const strippedLatin = originalLabel
        .replace(/,?\s*\d{3,4}\s*[-–]\s*(?:\d{3,4})?\s*$/u, '')
        .replace(/,/g, '')
        .trim();
      const latinOriginal = isLatinSurface(strippedLatin) ? strippedLatin : undefined;
      if (isTibetanLanguageCode(projectLang)) {
        candidate.romanizedName = generated ?? latinOriginal;
      } else {
        const enLabel = labels['en'];
        candidate.romanizedName =
          latinOriginal ??
          (enLabel && isLatinSurface(enLabel) ? enLabel : undefined) ??
          generated;
      }
    }

    if (
      candidate.projectLangName &&
      textMatchesProjectScript(candidate.projectLangName, projectLang) &&
      candidate.label !== candidate.projectLangName
    ) {
      candidate.label = candidate.projectLangName;
    }
  }
}

/** Normalize a pack row's typed-name entries; unrecognized categories fall back to `variant`. */
/**
 * Typed names from a pack row's `names[]`, for ingestion as *additional*
 * name elements (courtesy, art, posthumous, …). The primary/canonical entry
 * (CBDB's `c_name_chn`, typed "primary") is deliberately excluded — it's
 * already conveyed via `primaryName`/`projectLangName`, and re-adding it here
 * would risk a second `type="primary"` name element if normalization ever
 * puts it a character apart from the chosen canonical text.
 */
export function typedNamesFromPackRow(
  names: { text: string; type?: string; lang?: string }[] | undefined,
): TypedName[] | undefined {
  if (!names?.length) return undefined;
  const raw: TypedName[] = [];
  for (const name of names) {
    const text = name.text?.trim();
    if (!text) continue;
    const type = normalizeNameType(name.type) ?? 'variant';
    if (type === 'primary') continue;
    raw.push({ text, type, lang: name.lang });
  }
  const out = normalizeTypedNamesForIntake(raw);
  return out.length ? out : undefined;
}

/**
 * All typed names the chosen authority knows for a candidate: pack-provided
 * entries plus live Wikidata name-property claims (courtesy 字, posthumous
 * 諡號, …). Called at link time — one candidate, session-cached — and
 * best-effort: network failure returns whatever the packs had.
 */
export async function collectTypedNamesForCandidate(
  candidate: DisambiguationCandidate,
  fetchImpl?: typeof fetch,
): Promise<TypedName[]> {
  const byText = new Map<string, TypedName>();
  for (const name of candidate.typedNames ?? []) {
    byText.set(name.text.normalize('NFC'), name);
  }

  const qids = wikidataQidsForCandidate(candidate);
  if (qids.length > 0) {
    try {
      const byQid = await fetchWikidataTypedNames(qids, fetchImpl);
      for (const names of byQid.values()) {
        for (const name of names) {
          const key = name.text.normalize('NFC');
          if (!byText.has(key)) byText.set(key, name);
        }
      }
    } catch {
      // best-effort — pack names (if any) still apply
    }
  }

  const familyNames = [...byText.values()]
    .filter((name) => name.type === 'family')
    .map((name) => name.text);
  return normalizeTypedNamesForIntake([...byText.values()], familyNames);
}

/** Wikidata Q-ids a candidate is linked to (its URI, description, and Wikidata authority ids). */
function wikidataQidsForCandidate(candidate: DisambiguationCandidate): string[] {
  return [
    ...new Set([
      ...extractWikidataIdsFromText(candidate.uri),
      ...extractWikidataIdsFromText(candidate.description),
      ...(candidate.authorityIds ?? [])
        .filter((auth) => /^wikidata$/i.test(auth.type))
        .flatMap((auth) => extractWikidataIdsFromText(auth.value)),
    ]),
  ];
}

/**
 * Given/family name Wikidata knows for a candidate (P735/P734 — both point at
 * a Wikidata item for the name, resolved to a label). Best-effort: network
 * failure returns an empty result rather than throwing.
 */
export async function collectGivenFamilyNamesForCandidate(
  candidate: DisambiguationCandidate,
  projectLang?: string | null,
  fetchImpl?: typeof fetch,
): Promise<WikidataGivenFamilyNames> {
  const qids = wikidataQidsForCandidate(candidate);
  if (qids.length === 0) return {};
  try {
    const byQid = await fetchWikidataGivenFamilyNames(qids, projectLang, fetchImpl);
    for (const names of byQid.values()) {
      if (names.givenName || names.familyName) return names;
    }
  } catch {
    // best-effort
  }
  return {};
}

/** Non-Latin projects get deterministic project-script labels when rows merge. */
const mergeOptionsForLang = (projectLang?: string | null): MergeCandidateOptions | undefined =>
  isEastAsianCalendarLanguageCode(projectLang) || isTibetanLanguageCode(projectLang)
    ? { preferNonLatinLabel: true }
    : undefined;

export interface BuildDisambiguationCandidatesOptions {
  /** Wikidata lifespan enrichment for live hits (default true). */
  enrichLifespans?: boolean;
  /** Fill dual-script names via Wikidata (default true). */
  enrichNames?: boolean;
  /** Called once pack/local rows are ready, before live authorities finish. */
  onPartialResults?: (candidates: DisambiguationCandidate[]) => void;
}

export async function buildDisambiguationCandidates(
  entitiesDoc: Document | null,
  tag: string,
  surface: string,
  cache: AuthorityCache,
  enabledAuthorities: (keyof typeof AUTHORITY_MAP)[] = ['Wikidata', 'VIAF'],
  forceRefresh = false,
  readPackFile?: ReadAuthorityPackFile,
  dilaDetailCache?: DilaPlaceDetailCache,
  dilaFetchImpl?: DilaFetchFn,
  onDilaDatesReady?: () => void,
  projectLang?: string | null,
  /** Present only for a syncToCentral project - merges in matching CEDB entities. */
  central?: {
    doc?: Document;
    userStableId: string;
    /** Precomputed CEDB matches (already excluding PEDB-linked ids). */
    candidates?: DisambiguationCandidate[];
  },
  /** Proximity radius (km) for collapsing place candidates into geo clusters — see Phase 6. */
  placeProximityKm?: number,
  /** Precomputed PEDB matches; when set, `entitiesDoc` is not scanned. */
  localCandidates?: DisambiguationCandidate[],
  buildOptions?: BuildDisambiguationCandidatesOptions,
): Promise<DisambiguationCandidate[]> {
  const local =
    localCandidates ?? (entitiesDoc ? candidatesFromEntityFile(entitiesDoc, tag, surface) : []);
  const centralCandidates = central
    ? (central.candidates ??
      (() => {
        if (!central.doc || !entitiesDoc) return [];
        const linked = linkedCentralIds(entitiesDoc, central.userStableId);
        return candidatesFromEntityFile(central.doc, tag, surface, 'cedb').filter(
          (candidate) => !linked.has(candidate.centralEntityId!),
        );
      })())
    : [];
  const liveOptions: FetchLiveCandidatesOptions = {
    enrichLifespans: buildOptions?.enrichLifespans,
  };
  const packPromise = readPackFile
    ? candidatesFromAuthorityPacks(
        tag,
        surface,
        readPackFile,
        dilaDetailCache,
        dilaFetchImpl,
        onDilaDatesReady,
        projectLang,
      )
    : Promise.resolve([] as DisambiguationCandidate[]);
  // Start live fetch immediately so it overlaps pack reads.
  const livePromise = fetchLiveCandidates(
    tag,
    surface,
    cache,
    enabledAuthorities,
    forceRefresh,
    readPackFile,
    liveOptions,
  );

  const mergeOpts: MergeCandidateOptions = {
    ...mergeOptionsForLang(projectLang),
    tag,
    placeProximityKm,
  };
  const concordancePromise = readPackFile
    ? loadViafWikidataConcordance(readPackFile)
    : Promise.resolve(null);
  const bdrcConcordancePromise = readPackFile
    ? loadBdrcWikidataConcordance(readPackFile)
    : Promise.resolve(null);

  const finalize = async (
    packLocal: DisambiguationCandidate[],
    live: DisambiguationCandidate[],
  ) => {
    const index = (await concordancePromise) ?? null;
    let bdrcIndex = (await bdrcConcordancePromise) ?? emptyBdrcWikidataIndex();
    const merged = mergeCandidates([local, centralCandidates, packLocal, live], mergeOpts).map(
      enrichCandidateCrossRefs,
    );
    const viafEnriched = index
      ? enrichCandidatesWithViafWikidataConcordance(merged, index)
      : merged;
    const missing = qidsMissingBdrcLink(viafEnriched, bdrcIndex);
    if (missing.length > 0) {
      try {
        bdrcIndex = mergeBdrcWikidataIndexes(bdrcIndex, await fetchBdrcIdsForQids(missing));
      } catch {
        // Pack/concordance ids still apply when Wikidata is unreachable.
      }
    }
    const enriched = enrichCandidatesWithBdrcWikidataConcordance(viafEnriched, bdrcIndex);
    return collapseCrossAuthorityCandidates(enriched, mergeOpts);
  };

  const packLocal = await packPromise;
  if (buildOptions?.onPartialResults) {
    buildOptions.onPartialResults(await finalize(packLocal, []));
  }

  const live = await livePromise;
  const merged = await finalize(packLocal, live);
  if (buildOptions?.enrichNames !== false) {
    const kind = tag === 'name' ? 'person' : TAG_TO_KIND[tag];
    await enrichCandidateNames(merged, projectLang, undefined, kind ?? null);
  }
  return merged;
}

/** Map raw per-authority candidates into the shape SQLite enrich expects. */
export function toAuthoritySourcedFields(
  candidates: DisambiguationCandidate[] | undefined,
): AuthoritySourcedFields[] | undefined {
  if (!candidates?.length) return undefined;
  const mapped = candidates
    .map((candidate): AuthoritySourcedFields => {
      const source = (
        candidate.authoritySource ??
        candidate.authorityIds?.[0]?.type ??
        candidate.sources[0] ??
        'authority'
      ).toUpperCase();
      const meta = candidate.authorityMetadata;
      const metaBioYears = meta ? biographicalYearsFromMetadata(meta) : {};
      const metaFloruitYears = meta ? floruitYearsFromMetadata(meta) : {};
      // A candidate's authorityMetadata may carry only ancillary data (e.g.
      // nationality) with no date fields of its own — fall back to the
      // candidate's own startYear/endYear rather than treating "meta present"
      // as "meta is authoritative for dates".
      const hasMetaYears =
        metaBioYears.startYear != null ||
        metaBioYears.endYear != null ||
        metaFloruitYears.startYear != null ||
        metaFloruitYears.endYear != null;
      const fallbackYears = isFilterOnlyDateSource(candidate.dateSource)
        ? {}
        : candidate.dateSource === 'floruit'
          ? {}
          : {
              ...(candidate.startYear != null ? { startYear: candidate.startYear } : {}),
              ...(candidate.endYear != null ? { endYear: candidate.endYear } : {}),
            };
      const fallbackFloruitYears =
        candidate.dateSource === 'floruit'
          ? {
              ...(candidate.startYear != null ? { startYear: candidate.startYear } : {}),
              ...(candidate.endYear != null ? { endYear: candidate.endYear } : {}),
            }
          : {};
      const bioYears = hasMetaYears ? metaBioYears : fallbackYears;
      const floruitYears = hasMetaYears ? metaFloruitYears : fallbackFloruitYears;
      const asFloruit = Boolean(floruitYears.startYear != null || floruitYears.endYear != null);
      const years = asFloruit ? floruitYears : bioYears;
      return {
        source,
        startYear: years.startYear,
        endYear: years.endYear,
        ...(asFloruit ? { asFloruit: true } : {}),
        nationality: meta?.nationality?.map((value) => ({
          canonicalId: value.canonicalId,
          label: value.label,
        })),
        origin: meta?.origin,
        description:
          candidate.dateSource === 'index'
            ? scrubIndexYearFloruitClue(candidate.description)
            : candidate.description,
      };
    })
    .filter(
      (assertion) =>
        assertion.startYear != null ||
        assertion.endYear != null ||
        assertion.nationality?.length ||
        assertion.origin?.length ||
        assertion.description,
    );
  return mapped.length ? mapped : undefined;
}

/**
 * A CEDB-origin candidate (from a syncToCentral project's merged disambiguation
 * search) must be adopted into the PEDB first — this mints/reuses a linked
 * project mirror and rewrites the candidate to look like an ordinary local
 * match (`localEntityId` set, `centralEntityId` cleared). Candidates without a
 * `centralEntityId` pass through unchanged.
 */
export async function resolveCandidateForPedb(
  candidate: DisambiguationCandidate,
  projectStore: EntityStore,
  centralStore: EntityStore,
  userStableId: string,
): Promise<DisambiguationCandidate> {
  if (!candidate.centralEntityId) return candidate;
  const adopted = await adoptFromCentralSqlite(
    projectStore,
    centralStore,
    candidate.centralEntityId,
    userStableId,
  );
  if (!adopted) throw new Error(`adopt: central entity not found: ${candidate.centralEntityId}`);
  return { ...candidate, localEntityId: adopted.pedbId, centralEntityId: undefined };
}
