/**
 * Model for the entity database `entities.xml` (Phase 3): a TEI standoff
 * personography/placeography that holds disambiguated entities with typed local
 * ids and authority `<idno>`s. Mentions point in with a bare `@key`.
 */

const TEI_NS = 'http://www.tei-c.org/ns/1.0';
const XML_NS = 'http://www.w3.org/XML/1998/namespace';

export const DATABASE_IDNO_TYPE = 'ljb-entity-database';
export const LJB_AUTOTAG_RESP = '#ljb-autotag';
export const LJB_RESP = 'le-jean-baptiste';

/** @deprecated Use LJB_AUTOTAG_RESP */
export const LEAFWRITER_AUTOTAG_RESP = LJB_AUTOTAG_RESP;

export type EntityKind = 'person' | 'place' | 'org' | 'work';

interface KindConfig {
  /** Containing TEI list element. */
  list: string;
  /** Entity item element. */
  item: string;
  /** Name element written from the surface form. */
  name: string;
  /** xml:id prefix and the id-scan pattern. */
  idPrefix: string;
}

export const ENTITY_KINDS: Record<EntityKind, KindConfig> = {
  person: { list: 'listPerson', item: 'person', name: 'persName', idPrefix: 'person' },
  place: { list: 'listPlace', item: 'place', name: 'placeName', idPrefix: 'place' },
  org: { list: 'listOrg', item: 'org', name: 'orgName', idPrefix: 'org' },
  work: { list: 'listBibl', item: 'bibl', name: 'title', idPrefix: 'work' },
};

/** Mention tag name → entity kind. */
export const TAG_TO_KIND: Record<string, EntityKind> = {
  persName: 'person',
  placeName: 'place',
  orgName: 'org',
  title: 'work',
  bibl: 'work',
};

const ID_WIDTH = 6;

export interface AuthorityId {
  /** Canonical type, e.g. CBDB, Wikidata, VIAF, DILA, CHGIS, GeoNames. */
  type: string;
  value: string;
}

export interface NewEntity {
  /** Surface/display name for the entity. */
  name: string;
  authorityIds?: AuthorityId[];
  /** Optional compact authority-cache payload, stored as a JSON note. */
  cache?: { source: string; data: unknown; when?: string };
}

/** Mint a new database fingerprint id. */
export function newDatabaseId(): string {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  return `ljb-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

/** An empty entity file: TEI standoff with the four core lists. */
export function createEntitiesScaffold(databaseId: string = newDatabaseId()): string {
  const lists = Object.values(ENTITY_KINDS)
    .map((k) => `<${k.list}/>`)
    .join('\n      ');
  return `<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="${TEI_NS}">
  <teiHeader>
    <fileDesc>
      <titleStmt><title>Entity database</title></titleStmt>
      <publicationStmt>
        <p>Generated by Le Jean-Baptiste.</p>
        <idno type="${DATABASE_IDNO_TYPE}">${databaseId}</idno>
      </publicationStmt>
      <sourceDesc><p>Entity authority file.</p></sourceDesc>
    </fileDesc>
  </teiHeader>
  <standOff>
      ${lists}
  </standOff>
</TEI>`;
}

const parser = () => new DOMParser();

export function parseEntities(xml: string): Document {
  return parser().parseFromString(xml, 'application/xml');
}

export function serializeEntities(doc: Document): string {
  return new XMLSerializer().serializeToString(doc);
}

/** Read the database fingerprint from the TEI header. */
export function getDatabaseId(doc: Document): string | null {
  const idnos = doc.getElementsByTagName('idno');
  for (let i = 0; i < idnos.length; i++) {
    const el = idnos.item(i);
    if (el?.getAttribute('type') === DATABASE_IDNO_TYPE) {
      return el.textContent?.trim() || null;
    }
  }
  return null;
}

/** True when the document is a valid LJB entity database file. */
export function isEntityDatabase(doc: Document): boolean {
  if (!doc.documentElement || doc.documentElement.localName !== 'TEI') return false;
  if (!doc.getElementsByTagName('standOff')[0]) return false;
  return Boolean(getDatabaseId(doc));
}

/** Every xml:id currently in the document. */
function allIds(doc: Document): Set<string> {
  const ids = new Set<string>();
  const walker = doc.createTreeWalker(doc.documentElement, NodeFilter.SHOW_ELEMENT);
  for (let node = walker.currentNode as Element | null; node; node = walker.nextNode() as Element | null) {
    const id = node.getAttribute('xml:id');
    if (id) ids.add(id);
  }
  return ids;
}

/**
 * Next unused id for a kind: scan existing ids of that type, take the highest
 * suffix + 1, and skip any id already present (collision-safe). Ids are never
 * derived from names.
 */
export function nextEntityId(doc: Document, kind: EntityKind): string {
  const { idPrefix } = ENTITY_KINDS[kind];
  const ids = allIds(doc);
  const re = new RegExp(`^${idPrefix}-(\\d+)$`);
  let max = 0;
  for (const id of ids) {
    const match = re.exec(id);
    if (match) max = Math.max(max, parseInt(match[1]!, 10));
  }
  let next = max + 1;
  let candidate = `${idPrefix}-${String(next).padStart(ID_WIDTH, '0')}`;
  while (ids.has(candidate)) {
    next += 1;
    candidate = `${idPrefix}-${String(next).padStart(ID_WIDTH, '0')}`;
  }
  return candidate;
}

/** Get (creating if needed) the list element for a kind. */
function getList(doc: Document, kind: EntityKind): Element {
  const { list } = ENTITY_KINDS[kind];
  const existing = doc.getElementsByTagName(list)[0];
  if (existing) return existing;
  const standOff =
    doc.getElementsByTagName('standOff')[0] ?? doc.documentElement;
  const el = doc.createElementNS(TEI_NS, list);
  standOff.appendChild(el);
  return el;
}

/**
 * Add an entity to the file and return its new local id. `resp` marks
 * provenance (e.g. "#ljb-autotag" for machine auto-resolution).
 */
export function addEntity(
  doc: Document,
  kind: EntityKind,
  entity: NewEntity,
  resp?: string,
): { id: string; element: Element } {
  const config = ENTITY_KINDS[kind];
  const id = nextEntityId(doc, kind);

  const item = doc.createElementNS(TEI_NS, config.item);
  item.setAttributeNS(XML_NS, 'xml:id', id);
  if (resp) item.setAttribute('resp', resp);

  const name = doc.createElementNS(TEI_NS, config.name);
  name.textContent = entity.name;
  item.appendChild(name);

  for (const authority of entity.authorityIds ?? []) {
    const idno = doc.createElementNS(TEI_NS, 'idno');
    idno.setAttribute('type', authority.type);
    idno.textContent = authority.value;
    item.appendChild(idno);
  }

  if (entity.cache) {
    const note = doc.createElementNS(TEI_NS, 'note');
    note.setAttribute('type', 'authority-cache');
    note.setAttribute('source', entity.cache.source);
    note.setAttribute('resp', LJB_RESP);
    note.setAttribute('when', entity.cache.when ?? new Date().toISOString());
    note.textContent = JSON.stringify(entity.cache.data);
    item.appendChild(note);
  }

  getList(doc, kind).appendChild(item);
  return { id, element: item };
}

/** Find an entity element by its local id. */
export function findEntity(doc: Document, id: string): Element | null {
  const walker = doc.createTreeWalker(doc.documentElement, NodeFilter.SHOW_ELEMENT);
  for (let node = walker.currentNode as Element | null; node; node = walker.nextNode() as Element | null) {
    if (node.getAttribute('xml:id') === id) return node;
  }
  return null;
}
