import fs from 'fs/promises';
import os from 'os';
import path from 'path';
import {
  ALL_ENTITY_KINDS,
  getEntityById,
  readCombinedStatus,
  searchEntities,
} from './pluginEntities';
import { EntitySqliteRepository } from '../../../desktop/src/entityDbSqlite/repository';
import { importEntitiesXml } from '../../../desktop/src/entityDbSqlite/xmlCodec';

const FIXTURE_DATABASE_ID = 'b1e98777-6266-413b-b125-7f6d5ec5bcc8';

const FIXTURE_XML = `<?xml version="1.0" encoding="UTF-8"?><TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt><title>Entity database</title></titleStmt>
      <publicationStmt>
        <p>Generated by Grognard.</p>
        <idno type="grognard-entity-database">${FIXTURE_DATABASE_ID}</idno>
      </publicationStmt>
      <sourceDesc><p>Entity authority file.</p></sourceDesc>
    </fileDesc>
  </teiHeader>
  <standOff>
    <listPerson>
      <person xml:id="person-liu-xuan"><persName xml:lang="zh-Hant" type="primary">劉暄</persName><persName xml:lang="zh-Latn">Liu Xuan</persName><idno type="Wikidata">Q120698544</idno></person>
      <person xml:id="person-cui-zusi"><persName xml:lang="zh-Hant" type="primary">崔祖思</persName><persName xml:lang="zh-Latn">Cuī Zǔsī</persName><note type="dates">0440/0483</note></person>
      <person xml:id="person-jiang-shi"><persName xml:lang="zh-Hant" type="primary">江祏</persName><persName xml:lang="zh-Latn">Jiang Shi</persName><death when="0499" precision="d."/></person>
      <person xml:id="person-bce-example"><persName xml:lang="zh-Hant" type="primary">example</persName><persName xml:lang="zh-Latn">Example</persName><birth when="-0100" precision="b. ca."/><death when="-0050"/></person>
      <person xml:id="person-floruit-example"><persName xml:lang="zh-Hant" type="primary">fl-example</persName><persName xml:lang="zh-Latn">Fl Example</persName><birth when="0400" precision="fl."/></person>
    </listPerson>
    <listPlace/>
    <listOrg/>
    <listBibl>
      <bibl xml:id="work-nqs"><title xml:lang="zh-Hant" type="primary">南齊書</title><title xml:lang="zh-Latn">Nan Qi Shu</title><note type="description">history book about Southern Qi</note></bibl>
    </listBibl>
  </standOff>
</TEI>`;

const CENTRAL_DATABASE_ID = 'c2f6e0a1-1111-2222-3333-444455556666';

const CENTRAL_FIXTURE_XML = `<?xml version="1.0" encoding="UTF-8"?><TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt><title>Entity database</title></titleStmt>
      <publicationStmt>
        <p>Generated by Grognard.</p>
        <idno type="grognard-entity-database">${CENTRAL_DATABASE_ID}</idno>
      </publicationStmt>
      <sourceDesc><p>Entity authority file.</p></sourceDesc>
    </fileDesc>
  </teiHeader>
  <standOff>
    <listPerson>
      <person xml:id="person-liu-xuan"><persName xml:lang="zh-Hant" type="primary">劉暄</persName><persName xml:lang="zh-Latn">Liu Xuan</persName></person>
      <person xml:id="person-central-only"><persName xml:lang="zh-Hant" type="primary">中央</persName><persName xml:lang="zh-Latn">Central Only</persName></person>
    </listPerson>
    <listPlace/>
    <listOrg/>
    <listBibl/>
  </standOff>
</TEI>`;

const seedSqliteRoot = (root: string, xml: string): void => {
  const repository = new EntitySqliteRepository(path.join(root, 'entities.sqlite'));
  try {
    importEntitiesXml(repository, xml);
  } finally {
    repository.close();
  }
};

describe('pluginEntities', () => {
  let projectRoot: string;

  beforeEach(async () => {
    projectRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'grognard-plugin-entities-'));
    seedSqliteRoot(projectRoot, FIXTURE_XML);
  });

  afterEach(async () => {
    await fs.rm(projectRoot, { recursive: true, force: true });
  });

  test('readCombinedStatus reports the database id when entities.sqlite exists', async () => {
    const status = await readCombinedStatus([projectRoot]);
    expect(status).toEqual({ entitiesFound: true, databaseId: FIXTURE_DATABASE_ID });
  });

  test('readCombinedStatus reports entitiesFound: false when no root has entities.sqlite', async () => {
    const emptyRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'grognard-plugin-empty-'));
    try {
      const status = await readCombinedStatus([emptyRoot]);
      expect(status).toEqual({ entitiesFound: false, databaseId: null });
    } finally {
      await fs.rm(emptyRoot, { recursive: true, force: true });
    }
  });

  test('readCombinedStatus ignores entities.xml-only roots', async () => {
    const xmlOnly = await fs.mkdtemp(path.join(os.tmpdir(), 'grognard-plugin-xml-only-'));
    try {
      await fs.writeFile(path.join(xmlOnly, 'entities.xml'), FIXTURE_XML, 'utf8');
      const status = await readCombinedStatus([xmlOnly]);
      expect(status).toEqual({ entitiesFound: false, databaseId: null });
      await expect(searchEntities([xmlOnly], 'liu', ['person'], 20)).resolves.toEqual([]);
    } finally {
      await fs.rm(xmlOnly, { recursive: true, force: true });
    }
  });

  test('readCombinedStatus reports the database id when only a later root has entities.sqlite', async () => {
    const emptyRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'grognard-plugin-empty-'));
    try {
      const status = await readCombinedStatus([emptyRoot, projectRoot]);
      expect(status).toEqual({ entitiesFound: true, databaseId: FIXTURE_DATABASE_ID });
    } finally {
      await fs.rm(emptyRoot, { recursive: true, force: true });
    }
  });

  test('searchEntities matches romanized names case-insensitively', async () => {
    const results = await searchEntities([projectRoot], 'liu xuan', ['person'], 20);
    expect(results.map((r) => r.id)).toEqual(['person-liu-xuan']);
  });

  test('searchEntities matches Chinese characters', async () => {
    const results = await searchEntities([projectRoot], '劉暄', ['person'], 20);
    expect(results.map((r) => r.id)).toEqual(['person-liu-xuan']);
  });

  test('searchEntities ignores diacritics and spaces', async () => {
    const results = await searchEntities([projectRoot], 'cuizusi', ['person'], 20);
    expect(results.map((r) => r.id)).toEqual(['person-cui-zusi']);
  });

  test('searchEntities searches across all kinds when given the full kind list', async () => {
    const byDescription = await searchEntities([projectRoot], 'southern qi', ALL_ENTITY_KINDS, 20);
    expect(byDescription.map((r) => r.id)).toEqual(['work-nqs']);
  });

  test('searchEntities respects a kind filter', async () => {
    const filteredOut = await searchEntities([projectRoot], 'southern qi', ['person'], 20);
    expect(filteredOut).toEqual([]);
  });

  test('searchEntities respects the limit', async () => {
    const results = await searchEntities([projectRoot], '', ['person'], 1);
    expect(results.length).toBeLessThanOrEqual(1);
  });

  test('getEntityById returns full detail for a known id, with dates note padding stripped', async () => {
    const entity = await getEntityById([projectRoot], 'person-cui-zusi');
    expect(entity).toMatchObject({
      id: 'person-cui-zusi',
      kind: 'person',
      primaryName: '崔祖思',
      romanizedName: 'Cuī Zǔsī',
      dates: { startYear: 440, endYear: 483, startPrecision: null, endPrecision: null },
    });
  });

  test('getEntityById strips zero-padding from a death-only @when and carries its precision', async () => {
    const entity = await getEntityById([projectRoot], 'person-jiang-shi');
    expect(entity?.dates).toEqual({
      startYear: null,
      endYear: 499,
      startPrecision: null,
      endPrecision: 'd.',
    });
  });

  test('getEntityById formats BCE (negative) years without padding and carries precision per side', async () => {
    const entity = await getEntityById([projectRoot], 'person-bce-example');
    expect(entity?.dates).toEqual({
      startYear: -100,
      endYear: -50,
      startPrecision: 'b. ca.',
      endPrecision: null,
    });
  });

  test('getEntityById carries a floruit precision on a birth-only date', async () => {
    const entity = await getEntityById([projectRoot], 'person-floruit-example');
    expect(entity?.dates).toEqual({
      startYear: 400,
      endYear: null,
      startPrecision: 'fl.',
      endPrecision: null,
    });
  });

  test('getEntityById returns null for an unknown id', async () => {
    const entity = await getEntityById([projectRoot], 'person-does-not-exist');
    expect(entity).toBeNull();
  });

  test('searchEntities and getEntityById return empty/null when no root has entities.sqlite', async () => {
    const emptyRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'grognard-plugin-empty-'));
    try {
      await expect(searchEntities([emptyRoot], 'liu', ['person'], 20)).resolves.toEqual([]);
      await expect(getEntityById([emptyRoot], 'person-liu-xuan')).resolves.toBeNull();
    } finally {
      await fs.rm(emptyRoot, { recursive: true, force: true });
    }
  });

  describe('multiple roots (project + central)', () => {
    let centralRoot: string;

    beforeEach(async () => {
      centralRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'grognard-plugin-central-'));
      seedSqliteRoot(centralRoot, CENTRAL_FIXTURE_XML);
    });

    afterEach(async () => {
      await fs.rm(centralRoot, { recursive: true, force: true });
    });

    test('searchEntities finds a central-only entity when a project is also open', async () => {
      const results = await searchEntities(
        [projectRoot, centralRoot],
        'central only',
        ['person'],
        20,
      );
      expect(results.map((r) => r.id)).toEqual(['person-central-only']);
    });

    test('searchEntities finds project entities without a central root configured', async () => {
      const results = await searchEntities([projectRoot], 'liu xuan', ['person'], 20);
      expect(results.map((r) => r.id)).toEqual(['person-liu-xuan']);
    });

    test('searchEntities de-duplicates an id present in both roots, preferring the earlier (project) root', async () => {
      const results = await searchEntities([projectRoot, centralRoot], 'liu xuan', ['person'], 20);
      expect(results).toHaveLength(1);
      expect(results[0]?.id).toBe('person-liu-xuan');
      expect(results[0]?.authorityIds).toEqual([{ type: 'Wikidata', value: 'Q120698544' }]);
    });

    test('getEntityById finds a central-only entity when a project is also open', async () => {
      const entity = await getEntityById([projectRoot, centralRoot], 'person-central-only');
      expect(entity?.primaryName).toBe('中央');
    });

    test('readCombinedStatus prefers the project database id when both roots have SQLite', async () => {
      const status = await readCombinedStatus([projectRoot, centralRoot]);
      expect(status.databaseId).toBe(FIXTURE_DATABASE_ID);
    });
  });
});
