// Generated by visual_design/scripts/pack-assets.mjs — do not edit by hand.
// Regenerate by running `npm run visual-design:sync` whenever final assets
// or assets/worlds.json change in the (private) visual_design repo.

export interface ArchiveBackgroundAsset {
  readonly assetKey: string;
  readonly category: 'military' | 'memory' | 'easter-egg';
  readonly rank: number;
  /** Editorial photographic treatment, applied after the portrait is composited. */
  readonly treatment: 'colour' | 'wwi-ortho' | 'wwii-bw' | 'sepia' | 'tinted' | 'hand-coloured';
  readonly weight: number;
  /** 0-based pose indices that look compositionally wrong against this
   * specific backdrop (a lamppost through the head, a pose facing the
   * wrong way for the scene, etc) - Daniel's ongoing QA log in
   * visual_design/docs/bg-body-pairs.md, applied here so a background
   * this array names is never picked for that pose. Absent (not an empty
   * array) when this backdrop hasn't been reviewed yet or was reviewed
   * clean - see pickBackgroundKey's poseIndex filtering below. */
  readonly excludedPoses?: readonly number[];
}

/** Final backdrops grouped by world/rank (index 0 = Rank 1). The catalogue
 * takes precedence over legacy rewards/bg_<rank><variant>.png files for any
 * rank it declares. */
export const ARCHIVE_BACKGROUND_ASSETS_BY_RANK: readonly (readonly ArchiveBackgroundAsset[])[] =
  [
  [
    {
      "assetKey": "bg/r01/military/r01-artillery",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-artillery2",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5,
        6,
        11
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-barricade",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        6,
        8
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-breach",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        8
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-breach2",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5,
        8
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-by-the-sea",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5,
        11
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-camp",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-explosion",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        11
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-harbour2",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5,
        6,
        11
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-Paris2",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5,
        6
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-road-into-town",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5,
        11
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-road-into-town2",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-road-into-town3",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r01/military/r01-siege",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5,
        11
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-siege2",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r01/military/r01-urban-warfare",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        1,
        11
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-urban-warfare2",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5
      ]
    },
    {
      "assetKey": "bg/r01/military/r01-urban-warfare3",
      "category": "military",
      "rank": 1,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5,
        11
      ]
    }
  ],
  [
    {
      "assetKey": "bg/r02/easter-egg/r02-castle",
      "category": "easter-egg",
      "rank": 2,
      "treatment": "colour",
      "weight": 0.05
    },
    {
      "assetKey": "bg/r02/easter-egg/r02-dinosaurs",
      "category": "easter-egg",
      "rank": 2,
      "treatment": "colour",
      "weight": 0.05
    },
    {
      "assetKey": "bg/r02/easter-egg/r02-dragon",
      "category": "easter-egg",
      "rank": 2,
      "treatment": "colour",
      "weight": 0.05
    },
    {
      "assetKey": "bg/r02/easter-egg/r02-knights",
      "category": "easter-egg",
      "rank": 2,
      "treatment": "colour",
      "weight": 0.05
    },
    {
      "assetKey": "bg/r02/easter-egg/r02-kraken",
      "category": "easter-egg",
      "rank": 2,
      "treatment": "colour",
      "weight": 0.05
    },
    {
      "assetKey": "bg/r02/easter-egg/r02-mars",
      "category": "easter-egg",
      "rank": 2,
      "treatment": "colour",
      "weight": 0.05
    },
    {
      "assetKey": "bg/r02/easter-egg/r02-robot",
      "category": "easter-egg",
      "rank": 2,
      "treatment": "colour",
      "weight": 0.05,
      "excludedPoses": [
        5
      ]
    },
    {
      "assetKey": "bg/r02/easter-egg/r02-undersea",
      "category": "easter-egg",
      "rank": 2,
      "treatment": "colour",
      "weight": 0.05
    },
    {
      "assetKey": "bg/r02/military/r02-abbey",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        6,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-alps-road",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        6
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-artillery",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-baloons",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-birch-forest",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        2,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-bridge",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        6
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-camp",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        2,
        3,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-cavalry",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-cavalry-charge",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        6
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-family-portrait",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-Grand-Battery",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-Headquarters-Hill",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        6,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-ice-bridge2",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-island-fortress",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        6
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-italy1",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-italy3",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-logistics",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-marsh",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        1,
        7
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-moscow2",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-mountain-pass",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-Paris2",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3,
        7
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-pique-nique",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-pyramids",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-river-ford",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-ships-from-coast",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-Siege-Works",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-snow-battle",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-snow-retreat",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        5,
        6,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-snow-storm",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-spain1",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3,
        6,
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-spain2",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3,
        6,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r02/military/r02-standard",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r02/military/r02-windmills",
      "category": "military",
      "rank": 2,
      "treatment": "colour",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        11
      ]
    }
  ],
  [
    {
      "assetKey": "bg/r03/military/r03-artillery",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-artillery2",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-balloon",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-barracks",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-charge",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        3
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-city1",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-city2",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        5,
        7
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-command-bunker",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-comms",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-dawn-raid",
      "category": "military",
      "rank": 3,
      "treatment": "tinted",
      "weight": 1,
      "excludedPoses": [
        3
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-engineers",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-flyover",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-group-photo",
      "category": "military",
      "rank": 3,
      "treatment": "hand-coloured",
      "weight": 1
    },
    {
      "assetKey": "bg/r03/military/r03-hospital",
      "category": "military",
      "rank": 3,
      "treatment": "sepia",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-marsh",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-munitions",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-observation",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        8
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-observation2",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-prisoners",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-rush2",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        8
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-shelling1",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        3,
        5
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-shelling2",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1
    },
    {
      "assetKey": "bg/r03/military/r03-stretchers",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-supplies",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-supply-train",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-tank-advance",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-tank-advance2",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-tank-crossing",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-tank-immobilised",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        6,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-tank-point",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        6,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-tanks-in-mist",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        8
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-trench-flyby",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        3
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-trenches1",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        8
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-trenches2",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-trenches4",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r03/military/r03-trenchs3",
      "category": "military",
      "rank": 3,
      "treatment": "wwi-ortho",
      "weight": 1
    }
  ],
  [
    {
      "assetKey": "bg/r04/military/r04-a-airfield",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        6,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-a-artillery",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-a-avance",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-a-bridge",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-a-hospital",
      "category": "military",
      "rank": 4,
      "treatment": "sepia",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-a-tank-graveyard",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-a-tank-hedge",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-a-town",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-a-train-yard",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-a-trolly",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-airfield",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        8,
        9,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-bridge",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        6,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-calvary-meets-mech",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-collective-farm",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-dismantle",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-forest",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-pause",
      "category": "military",
      "rank": 4,
      "treatment": "tinted",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-propaganda",
      "category": "military",
      "rank": 4,
      "treatment": "hand-coloured",
      "weight": 1,
      "excludedPoses": [
        5
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-train-depo",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-train-ride",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        5,
        6,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-wheat-advance",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        1,
        2,
        3,
        5
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-wheat-fields",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-b-whole-army",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-ambush",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        5,
        7,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-another",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-bombing",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        6,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-crater",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-empty-gov",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-explosion",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-fountain",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        6,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-kremlin",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-monument-down",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        6,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-square-rush",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        5,
        7
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-tank-ambush",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-tank-wrecks",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        2,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-train-station-battle",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        1,
        2,
        5,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-c-trolly-pinned",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        2,
        3,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-abandoned-airfield",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        5,
        6,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-air-strike",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-ambush",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        2,
        3,
        4,
        5,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-army-building",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-ford",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        6,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-gorges",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-lower-yangtze",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        7,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-meetup",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        4,
        5,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-mud",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        6,
        7,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-nanking",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-over-the-mountains",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-paddies",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        2,
        3,
        4,
        5,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-saigon",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        2,
        5,
        6,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-shanghai",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-taiwan",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-d-Wuhan",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-airfield",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-crossing",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        1,
        3,
        5,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-japan-land",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-japanese-bunkers",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-kyushu-landing",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        1,
        2
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-naval-attack",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        6,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-okinawa",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-ryukyu-battle",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        8
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-ryukyu-landing",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        1,
        3,
        6
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-shipyards",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8,
        11
      ]
    },
    {
      "assetKey": "bg/r04/military/r04-e-towards-japan",
      "category": "military",
      "rank": 4,
      "treatment": "wwii-bw",
      "weight": 1,
      "excludedPoses": [
        3,
        5,
        7,
        8,
        11
      ]
    }
  ],
  [
    {
      "assetKey": "bg/r05/military/r05-a-boarding",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-a-duel",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-a-landing-bay",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-a-orbital-bombardement",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-b-apc-attack",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-b-clearing-house",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-b-farm",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-b-flag-bearer",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-b-plaza",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-b-road",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-b-spire",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-b-temple",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-b-trenches",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-c-orbital-defense-approach",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-c-orbital-defense-firing",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r05/military/r05-c-wall",
      "category": "military",
      "rank": 5,
      "treatment": "colour",
      "weight": 1
    }
  ],
  [
    {
      "assetKey": "bg/r06/military/r05-a-boarding",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-a-duel",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-a-landing-bay",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-a-orbital-bombardement",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-b-apc-attack",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-b-clearing-house",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-b-farm",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-b-flag-bearer",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-b-plaza",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-b-road",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-b-spire",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-b-temple",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-b-trenches",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-c-orbital-defense-approach",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-c-orbital-defense-firing",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r06/military/r05-c-wall",
      "category": "military",
      "rank": 6,
      "treatment": "colour",
      "weight": 1
    }
  ],
  [
    {
      "assetKey": "bg/r07/military/r05-a-boarding",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-a-duel",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-a-landing-bay",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-a-orbital-bombardement",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-b-apc-attack",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-b-clearing-house",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-b-farm",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-b-flag-bearer",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-b-plaza",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-b-road",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-b-spire",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-b-temple",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-b-trenches",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-c-orbital-defense-approach",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-c-orbital-defense-firing",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    },
    {
      "assetKey": "bg/r07/military/r05-c-wall",
      "category": "military",
      "rank": 7,
      "treatment": "colour",
      "weight": 1
    }
  ]
];

/** Allowed reusable body poses by world/rank. A null entry preserves the
 * historical generic pool until that world has an explicit design decision. */
export const WORLD_BODY_POOLS: readonly (readonly number[] | null)[] =
  [
  [
    1,
    5,
    6,
    8,
    11
  ],
  [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    11
  ],
  [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    11,
    9001
  ],
  [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    11
  ],
  [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    10,
    11
  ],
  [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    10,
    11
  ],
  [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    10,
    11
  ]
];

/** Compatibility export for code that only needs the backdrop keys. */
export const BG_POOL_BY_RANK: readonly string[][] = ARCHIVE_BACKGROUND_ASSETS_BY_RANK.map(
  (assets) => assets.map((asset) => asset.assetKey),
);
