// Generated by visual_design/scripts/generate-avatar-parts-manifest.mjs — do
// not edit by hand. Regenerate (via `npm run visual-design:sync`) whenever
// visual_style/*/ files are added/removed - every variant list here is a
// full, unfiltered scan of that category's folder, never a hand-picked
// shortlist.

export const EYEBROWS_VARIANTS: readonly string[] = ["variant01","variant02","variant03","variant04","variant05","variant06","variant07","variant08","variant09","variant10","variant11","variant12","variant13","variant14","variant15"];

export const EYES_VARIANTS: readonly string[] = ["variant01","variant02","variant03","variant04","variant05","variant06","variant07","variant08","variant09","variant10","variant11","variant12","variant13","variant14","variant15","variant16","variant17","variant18","variant19","variant20","variant21","variant22","variant23","variant24","variant25","variant26"];

export const MOUTH_VARIANTS: readonly string[] = ["variant01","variant02","variant03","variant04","variant05","variant06","variant07","variant08","variant09","variant10","variant11","variant12","variant13","variant14","variant15","variant16","variant17","variant18","variant19","variant20","variant21","variant22","variant23","variant24","variant25","variant26","variant27","variant28","variant29","variant30"];

export const GLASSES_VARIANTS: readonly string[] = ["variant01","variant02","variant03","variant04","variant05"];

export const HAIR_VARIANTS: readonly string[] = ["long01","long02","long03","long04","long05","long06","long07","long08","long09","long10","long11","long12","long13","long14","long15","long16","long17","long18","long19","long20","long21","long22","long23","long24","long25","long26","short01","short02","short03","short04","short05","short06","short07","short08","short09","short10","short11","short12","short13","short14","short15","short16","short17","short18","short19"];

export const FEATURES_VARIANTS: readonly string[] = ["birthmark","blush","freckles","mustache"];

export const EARRINGS_VARIANTS: readonly string[] = ["variant01","variant02","variant03","variant04","variant05","variant06"];
