// Generated by visual_design/scripts/pack-assets.mjs — do not edit by hand.
// Regenerate whenever visual_design/bodies/body*.svg changes.
//
// POSE_INDICES: every pose that has a full f-rank1..7/m-rank1..7 kit (i.e.
// is eligible for the random pose pick in UniformAvatar.tsx) - excludes
// bodies/body0.svg, the civilian body (still packed as body/pose0 for the
// fixed Civil portrait).
//
// WEAPON_POOLS: per pose index, one entry per <g inkscape:label="weapons">
// block found in that pose's SVG (a pose can have zero, one, or two - two
// when a weapon is split into rear/front halves across background/
// foreground layers, e.g. body6.svg). Each entry maps rank number -> a
// WeaponRankPool: "universal" ids show regardless of bodyType (a plain
// rankN label); "f"/"m" are only present when that rank has a bodyType-
// specific piece (an f-rankN/m-rankN label), keyed by variant - '' for a
// plain f-rankN with no letter suffix, or the letter(s) after the dash for
// mutually exclusive alternates (body6.svg's f-rank2-a vs f-rank2-b). More
// than one id sharing the same bucket means simultaneous parts of the same
// design (e.g. body7.svg's rank2 sits one image per hand, not two
// alternates), all shown together. Opaque ids, not spoilers - they mean
// nothing without the encrypted artwork itself.
//
// BODY_COLOR_STATS: one precomputed lightness/saturation stat per
// "<poseIndex>:<bodyType>" key, sampled from a representative rank-1, no-
// weapon render - see colorMatch.ts/getHeadColorStats for the equivalent
// head-side table this mirrors. Includes pose 0 (civilian).

import type { ColorStats } from './colorMatch';

export interface WeaponRankPool {
  readonly universal: readonly string[];
  readonly f?: Readonly<Record<string, readonly string[]>>;
  readonly m?: Readonly<Record<string, readonly string[]>>;
}

export const POSE_INDICES: readonly number[] = [1,2,3,4,5,6,7];

export const WEAPON_POOLS: Readonly<Record<number, ReadonlyArray<Record<number, WeaponRankPool>>>> =
  {
  "1": [],
  "2": [],
  "3": [],
  "4": [],
  "5": [
    {
      "1": {
        "universal": [
          "image1-04"
        ]
      },
      "2": {
        "universal": [
          "image1-9"
        ]
      },
      "3": {
        "universal": [
          "image1-854"
        ]
      },
      "4": {
        "universal": [
          "image1-6"
        ]
      }
    }
  ],
  "6": [
    {
      "1": {
        "universal": [],
        "f": {
          "a": [
            "image412"
          ]
        },
        "m": {
          "a": [
            "image405"
          ]
        }
      },
      "2": {
        "universal": [],
        "f": {
          "a": [
            "image400"
          ]
        },
        "m": {
          "a": [
            "image397"
          ]
        }
      },
      "3": {
        "universal": [],
        "f": {
          "a": [
            "image1-36"
          ]
        },
        "m": {
          "a": [
            "image7"
          ]
        }
      },
      "4": {
        "universal": [],
        "f": {
          "b": [
            "image396"
          ]
        },
        "m": {
          "b": [
            "image395"
          ]
        }
      },
      "5": {
        "universal": [],
        "f": {
          "a": [
            "image391",
            "image392"
          ],
          "b": [
            "image413"
          ]
        },
        "m": {
          "a": [
            "image11",
            "image12"
          ],
          "b": [
            "image415"
          ]
        }
      }
    },
    {
      "1": {
        "universal": [],
        "f": {
          "a": [
            "image1-768"
          ]
        },
        "m": {
          "a": [
            "image404"
          ]
        }
      },
      "2": {
        "universal": [],
        "f": {
          "a": [
            "image1-97",
            "image399"
          ]
        },
        "m": {
          "a": [
            "image1-9"
          ]
        }
      },
      "3": {
        "universal": [],
        "f": {
          "a": [
            "image6"
          ]
        },
        "m": {
          "a": [
            "image8"
          ]
        }
      },
      "4": {
        "universal": [],
        "f": {
          "a": [
            "image5"
          ],
          "b": [
            "image394"
          ]
        },
        "m": {
          "b": [
            "image1-04"
          ],
          "a": [
            "image2"
          ]
        }
      },
      "5": {
        "universal": [],
        "f": {
          "a": [
            "image1-79"
          ],
          "b": [
            "image401"
          ]
        },
        "m": {
          "a": [
            "image390"
          ],
          "b": [
            "image414"
          ]
        }
      }
    }
  ],
  "7": [
    {
      "2": {
        "universal": [
          "image1-52",
          "image1-97"
        ]
      },
      "3": {
        "universal": [
          "image1-1",
          "image1-22"
        ]
      },
      "4": {
        "universal": [
          "image1-760",
          "image9"
        ]
      },
      "5": {
        "universal": [
          "image1-79",
          "image1-70",
          "image1-75"
        ]
      }
    }
  ]
};

export const BODY_COLOR_STATS: Readonly<Record<string, ColorStats>> = {
  "0:m": {
    "lightness": 0.20524546866101945,
    "saturation": 0.13953426043894415
  },
  "0:f": {
    "lightness": 0.15782304091615793,
    "saturation": 0.13022940578439354
  },
  "1:m": {
    "lightness": 0.2430278149103234,
    "saturation": 0.7518017100170777
  },
  "1:f": {
    "lightness": 0.27692572926005943,
    "saturation": 0.71501128502576
  },
  "2:m": {
    "lightness": 0.3462723927919635,
    "saturation": 0.7467161106363289
  },
  "2:f": {
    "lightness": 0.32935814610414493,
    "saturation": 0.6711772346884606
  },
  "3:m": {
    "lightness": 0.3284507615123122,
    "saturation": 0.6830626567861804
  },
  "3:f": {
    "lightness": 0.33549611641086774,
    "saturation": 0.7325838313155693
  },
  "4:m": {
    "lightness": 0.3381955235752437,
    "saturation": 0.6731212028542185
  },
  "4:f": {
    "lightness": 0.3166763406800682,
    "saturation": 0.7339473172178462
  },
  "5:m": {
    "lightness": 0.4393589613853619,
    "saturation": 0.6813891079772731
  },
  "5:f": {
    "lightness": 0.44592791614732347,
    "saturation": 0.7041345282314619
  },
  "6:m": {
    "lightness": 0.3387063985349195,
    "saturation": 0.7025048220852016
  },
  "6:f": {
    "lightness": 0.3344217851120945,
    "saturation": 0.7544283438371846
  },
  "7:m": {
    "lightness": 0.38290093700004146,
    "saturation": 0.5517742555238363
  },
  "7:f": {
    "lightness": 0.39870205560965766,
    "saturation": 0.5794844005979924
  }
};
