// Generated by visual_design/scripts/pack-assets.mjs — do not edit by hand.
// Regenerate whenever visual_design/bodies/body*.svg changes.
//
// POSE_INDICES: every pose that has a full f-rank1..7/m-rank1..7 kit (i.e.
// is eligible for the random pose pick in UniformAvatar.tsx) - excludes
// bodies/body0.svg, the civilian body (still packed as body/pose0 for the
// fixed Civil portrait).
//
// WEAPON_POOLS: per pose index, one entry per <g inkscape:label="weapons">
// block found in that pose's SVG (a pose can have zero, one, or two - two
// when a weapon is split into rear/front halves across background/
// foreground layers, e.g. body6.svg). Each entry maps rank number (a tier
// unlocked at that world rank - see WEAPON_ERA_TIERS in bodySvg.mjs, which
// is why these numbers can be sparse, e.g. {1,3,4,5} rather than {1,2,3,4})
// to a WeaponRankPool: "universal" is always present and applies regardless
// of bodyType (a bare era label); "f"/"m" are only present when that rank
// has a bodyType-specific piece (an f-/m- prefixed label). Each of those is
// a WeaponScope: Record<group, Record<variant, ids[]>>. Group '' is the
// default, used by most poses (body6.svg's napoleonic1/2/3 - three
// different muskets in the one default group); a named group (body7.svg's
// "pistol"/"sword") is an independent equipment slot, worn simultaneously
// with every other group present - not an alternative to choose between -
// while cycling its own variants independently of any other group's pick
// (which sword shows is independent of which pistol shows). Within a
// group, each variant key is a mutually-exclusive alternate design; more
// than one id sharing the same variant means simultaneous parts of the
// same design (e.g. body7.svg's sword pieces, one per hand), all shown
// together. Opaque ids, not spoilers - they mean nothing without the
// encrypted artwork itself.
//
// BODY_COLOR_STATS: one precomputed lightness/saturation stat per
// "<poseIndex>:<bodyType>" key, sampled from a representative render at the
// pose's own lowest available rank (usually rank 1; see
// POSE_ASSET_MIN_RANK_INDEX below for poses where that isn't 1), no weapon -
// see colorMatch.ts/getHeadColorStats for the equivalent head-side table
// this mirrors. Includes pose 0 (civilian).
//
// POSE_ASSET_MIN_RANK_INDEX: 0-based rank index below which a pose has no
// art at all (e.g. a subject SVG may only have rank2-and-up groups, so its entry here is
// 1) - sparse, only poses that don't start at rank 1. This is a hard floor
// from what the SVG actually contains; UniformAvatar.tsx's own
// POSE_MIN_RANK_INDEX layers additional *design* gating on top (a pose that
// has full art from rank 1 but is deliberately held back for pacing
// reasons) - the two are independent and combined at call sites.

import type { ColorStats } from './colorMatch';

export type WeaponScope = Readonly<Record<string, Readonly<Record<string, readonly string[]>>>>;

export interface WeaponRankPool {
  readonly universal: WeaponScope;
  readonly f?: WeaponScope;
  readonly m?: WeaponScope;
}

export const POSE_INDICES: readonly number[] = [1,2,3,4,5,6,7,8,10,11,9001];

export const POSE_ASSET_MIN_RANK_INDEX: Readonly<Record<number, number>> =
  {
  "9001": 1
};

export const POSE_AVAILABLE_RANK_INDICES: Readonly<Record<number, readonly number[]>> =
  {
  "9001": [
    2
  ]
};

export const WEAPON_POOLS: Readonly<Record<number, readonly Record<number, WeaponRankPool>[]>> =
  {
  "1": [],
  "2": [],
  "3": [],
  "4": [],
  "5": [
    {
      "1": {
        "universal": {
          "": {
            "1": [
              "image1-04"
            ],
            "2": [
              "image1-83"
            ]
          }
        }
      },
      "3": {
        "universal": {
          "": {
            "1": [
              "image1-1-9"
            ],
            "2": [
              "image1-4-0"
            ],
            "3": [
              "image1-40"
            ]
          }
        }
      },
      "4": {
        "universal": {
          "": {
            "1": [
              "image1-7"
            ]
          }
        }
      },
      "5": {
        "universal": {
          "": {
            "1": [
              "image1-02"
            ]
          }
        }
      }
    }
  ],
  "6": [
    {
      "1": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image412"
            ],
            "2": [
              "image14"
            ],
            "3": [
              "image400"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image82"
            ],
            "2": [
              "image80"
            ],
            "3": [
              "image397"
            ]
          }
        }
      },
      "3": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image53"
            ],
            "2": [
              "image69"
            ],
            "3": [
              "image74"
            ],
            "4": [
              "image77"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image22"
            ],
            "2": [
              "image45"
            ],
            "3": [
              "image46"
            ],
            "4": [
              "image51"
            ]
          }
        }
      },
      "4": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image19"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image23"
            ],
            "2": [
              "image21"
            ],
            "3": [
              "image20"
            ]
          }
        }
      },
      "5": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image55"
            ],
            "2": [
              "image1-0248"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image1-024"
            ],
            "2": [
              "image56"
            ]
          }
        }
      }
    },
    {
      "1": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image86"
            ],
            "2": [
              "image88"
            ],
            "3": [
              "image90"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image405"
            ],
            "2": [
              "image15"
            ],
            "3": [
              "image84"
            ]
          }
        }
      },
      "3": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image52"
            ],
            "2": [
              "image67"
            ],
            "3": [
              "image73"
            ],
            "4": [
              "image76"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image1-67"
            ],
            "2": [
              "image1-2"
            ],
            "3": [
              "image1-6-7"
            ],
            "4": [
              "image1-70"
            ]
          }
        }
      },
      "4": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image18"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image1-0-9"
            ],
            "2": [
              "image1-67-0"
            ],
            "3": [
              "image1-046"
            ]
          }
        }
      },
      "5": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image24"
            ],
            "2": [
              "image26"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image25"
            ],
            "2": [
              "image70"
            ]
          }
        }
      }
    }
  ],
  "7": [
    {
      "1": {
        "universal": {},
        "f": {
          "pistol": {
            "": [
              "image1-52"
            ]
          },
          "sword": {
            "1": [
              "image1-97"
            ],
            "2": [
              "image1-02"
            ]
          }
        },
        "m": {
          "sword": {
            "1": [
              "image4"
            ],
            "2": [
              "image3"
            ]
          },
          "pistol": {
            "": [
              "image5"
            ]
          }
        }
      },
      "3": {
        "universal": {},
        "f": {
          "pistol": {
            "1": [
              "image20"
            ],
            "2": [
              "image19"
            ],
            "4": [
              "image17"
            ],
            "5": [
              "image16"
            ]
          },
          "sword": {
            "": [
              "image21"
            ]
          }
        },
        "m": {
          "pistol": {
            "1": [
              "image1-03"
            ],
            "2": [
              "image1-8-3"
            ],
            "3": [
              "image1-72"
            ],
            "4": [
              "image1-5"
            ]
          },
          "sword": {
            "": [
              "image1-02-8"
            ]
          }
        }
      },
      "4": {
        "universal": {},
        "f": {
          "sword": {
            "": [
              "image1"
            ]
          },
          "pistol": {
            "1": [
              "image12"
            ],
            "2": [
              "image11"
            ],
            "3": [
              "image10"
            ]
          }
        },
        "m": {
          "sword": {
            "": [
              "image1-91-5"
            ]
          },
          "pistol": {
            "1": [
              "image1-3"
            ],
            "2": [
              "image1-03-5"
            ],
            "3": [
              "image1-83"
            ]
          }
        }
      },
      "5": {
        "universal": {},
        "f": {
          "pistol": {
            "1": [
              "image1-74"
            ],
            "2": [
              "image1-522"
            ]
          },
          "sword": {
            "1": [
              "image1-84"
            ],
            "2": [
              "image29"
            ]
          }
        },
        "m": {
          "sword": {
            "1": [
              "image25"
            ],
            "2": [
              "image1-78"
            ]
          },
          "pistol": {
            "1": [
              "image24"
            ],
            "2": [
              "image18"
            ]
          }
        }
      }
    },
    {
      "3": {
        "universal": {},
        "f": {
          "sword": {
            "": [
              "image23"
            ]
          }
        },
        "m": {
          "sword": {
            "": [
              "image1-4"
            ]
          }
        }
      },
      "4": {
        "universal": {},
        "f": {
          "sword": {
            "": [
              "image9"
            ]
          }
        },
        "m": {
          "sword": {
            "": [
              "image1-41"
            ]
          }
        }
      },
      "5": {
        "universal": {},
        "f": {
          "sword": {
            "1": [
              "image1-723"
            ]
          }
        },
        "m": {
          "sword": {
            "1": [
              "image30"
            ]
          }
        }
      }
    }
  ],
  "8": [
    {
      "1": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image1"
            ],
            "2": [
              "image1-85"
            ],
            "3": [
              "image1-9"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image89"
            ],
            "2": [
              "image88"
            ],
            "3": [
              "image90"
            ]
          }
        }
      },
      "3": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image5"
            ],
            "2": [
              "image4"
            ],
            "3": [
              "image3"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image1-2"
            ],
            "2": [
              "image1-6"
            ],
            "3": [
              "image1-70"
            ]
          }
        }
      },
      "4": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image1-1-8"
            ],
            "2": [
              "image1-0-4"
            ],
            "3": [
              "image1-91"
            ]
          }
        },
        "m": {
          "": {
            "2": [
              "image7"
            ],
            "3": [
              "image6"
            ]
          }
        }
      },
      "5": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image2"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image1-02"
            ]
          }
        }
      }
    }
  ],
  "10": [
    {
      "5": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "image1"
            ],
            "2": [
              "image7"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "image2"
            ],
            "2": [
              "image1-0"
            ]
          }
        }
      }
    }
  ],
  "11": [
    {
      "1": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "g29",
              "image412",
              "image60"
            ],
            "2": [
              "g31",
              "image30",
              "image1-7"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "g3",
              "image1-19",
              "image405",
              "image1-6"
            ],
            "2": [
              "g5",
              "image3",
              "image15",
              "image5"
            ]
          }
        }
      },
      "3": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "g60",
              "image59",
              "image61"
            ],
            "2": [
              "g57",
              "image56",
              "image62"
            ],
            "3": [
              "g54",
              "image53",
              "image63"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "g8",
              "image6",
              "image45",
              "image8"
            ],
            "2": [
              "g11",
              "image9",
              "image46",
              "image11"
            ],
            "3": [
              "g16",
              "image12",
              "image51",
              "image16"
            ]
          }
        }
      },
      "4": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "g50",
              "image49",
              "image64"
            ],
            "2": [
              "g42",
              "image41",
              "image65"
            ],
            "3": [
              "g39",
              "image37",
              "image66"
            ],
            "4": [
              "g36",
              "image32",
              "image67"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "g22",
              "image20",
              "image21",
              "image22"
            ],
            "2": [
              "g19",
              "image17",
              "image1-0-0",
              "image19"
            ],
            "3": [
              "g25",
              "image23",
              "image1-71",
              "image25"
            ],
            "4": [
              "g28",
              "image26",
              "image1-77",
              "image28"
            ]
          }
        }
      },
      "5": {
        "universal": {},
        "f": {
          "": {
            "1": [
              "g10",
              "image1-94",
              "image7",
              "image1-01"
            ],
            "2": [
              "g18",
              "image13",
              "image24",
              "image18"
            ]
          }
        },
        "m": {
          "": {
            "1": [
              "g4",
              "image1-4",
              "image1",
              "image1-75"
            ],
            "2": [
              "g13",
              "image2",
              "image1-73",
              "image10"
            ]
          }
        }
      }
    }
  ],
  "9001": []
};

export const BODY_COLOR_STATS: Readonly<Record<string, ColorStats>> = {
  "0:m": {
    "lightness": 0.20524546866101945,
    "saturation": 0.13953426043894415
  },
  "0:f": {
    "lightness": 0.15782304091615793,
    "saturation": 0.13022940578439354
  },
  "1:m": {
    "lightness": 0.2430278149103234,
    "saturation": 0.7518017100170777
  },
  "1:f": {
    "lightness": 0.27692572926005943,
    "saturation": 0.71501128502576
  },
  "2:m": {
    "lightness": 0.3335627464944711,
    "saturation": 0.6959022119843489
  },
  "2:f": {
    "lightness": 0.3422078934404294,
    "saturation": 0.7272106428790185
  },
  "3:m": {
    "lightness": 0.3284507615123122,
    "saturation": 0.6830626567861804
  },
  "3:f": {
    "lightness": 0.33549611641086774,
    "saturation": 0.7325838313155693
  },
  "4:m": {
    "lightness": 0.3381955235752437,
    "saturation": 0.6731212028542185
  },
  "4:f": {
    "lightness": 0.3166763406800682,
    "saturation": 0.7339473172178462
  },
  "5:m": {
    "lightness": 0.4393589613853619,
    "saturation": 0.6813891079772731
  },
  "5:f": {
    "lightness": 0.44592791614732347,
    "saturation": 0.7041345282314619
  },
  "6:m": {
    "lightness": 0.3387063985349195,
    "saturation": 0.7025048220852016
  },
  "6:f": {
    "lightness": 0.3344217851120945,
    "saturation": 0.7544283438371846
  },
  "7:m": {
    "lightness": 0.3866325201534361,
    "saturation": 0.6224156876927419
  },
  "7:f": {
    "lightness": 0.41652766415760095,
    "saturation": 0.6674249548667511
  },
  "8:m": {
    "lightness": 0.3770245814712972,
    "saturation": 0.7340215192945299
  },
  "8:f": {
    "lightness": 0.3772693581700683,
    "saturation": 0.6595831214251591
  },
  "10:m": {
    "lightness": 0.29388070752776335,
    "saturation": 0.5673748584379388
  },
  "10:f": {
    "lightness": 0.27212966565660535,
    "saturation": 0.5586076270877643
  },
  "11:m": {
    "lightness": 0.2697734082503499,
    "saturation": 0.6658298681239084
  },
  "11:f": {
    "lightness": 0.31171002344959153,
    "saturation": 0.6699277200493944
  },
  "9001:m": {
    "lightness": 0.429479063180832,
    "saturation": 0.24572819881921504
  },
  "9001:f": {
    "lightness": 0.4288901307189572,
    "saturation": 0.244318614936471
  }
};
