// Generated by visual_design/scripts/pack-assets.mjs — do not edit by hand.
// Regenerate by running `npm run visual-design:sync` whenever rewards/bg_*
// files are added/removed in the (private) visual_design repo.

/** Rank-gated portrait backdrops, one letter-suffixed pool per rank (index 0
 * = rank I), derived from rewards/bg_<rank><variant>.png filenames - see
 * UniformAvatar.tsx for how these pools are used. */
export const BG_POOL_BY_RANK: readonly string[][] = [
  [
    "bg/1a",
    "bg/1b"
  ],
  [
    "bg/2a",
    "bg/2b",
    "bg/2c",
    "bg/2d",
    "bg/2e"
  ],
  [
    "bg/3a",
    "bg/3b",
    "bg/3c",
    "bg/3d",
    "bg/3e"
  ],
  [
    "bg/4a",
    "bg/4b",
    "bg/4c",
    "bg/4d"
  ],
  [
    "bg/5a",
    "bg/5b",
    "bg/5c",
    "bg/5d"
  ],
  [
    "bg/6a",
    "bg/6b",
    "bg/6c",
    "bg/6d",
    "bg/6e",
    "bg/6f"
  ],
  [
    "bg/7a",
    "bg/7b",
    "bg/7c",
    "bg/7d",
    "bg/7e",
    "bg/7f"
  ]
];
