// Generated by visual_design/scripts/generate-head-color-stats.mjs — do not
// edit by hand. Regenerate if the skin/hair color palette in dicebear.ts
// changes. Public data (no obfuscation): these are just average
// lightness/saturation numbers, not the artwork itself.
//
// Precomputed rather than sampled at runtime (see colorMatch.ts) - hair
// *length* (short vs long) noticeably shifts the average, so the table is
// keyed on that too; the specific hair/eyes/mouth shape within a length
// does not, so those are held fixed when the table was rendered.

import type { ColorStats } from './colorMatch';

const HEAD_COLOR_STATS: Record<string, ColorStats> = {
  'short|f2d3b1|0e0e0e': { lightness: 0.5286, saturation: 0.3769 },
  'short|f2d3b1|e5d7a3': { lightness: 0.6922, saturation: 0.5041 },
  'short|f2d3b1|6a4e35': { lightness: 0.5874, saturation: 0.4572 },
  'short|f2d3b1|cb6820': { lightness: 0.6216, saturation: 0.5529 },
  'short|f2d3b1|afafaf': { lightness: 0.6733, saturation: 0.3769 },
  'short|ecad80|0e0e0e': { lightness: 0.4727, saturation: 0.3963 },
  'short|ecad80|e5d7a3': { lightness: 0.6363, saturation: 0.5236 },
  'short|ecad80|6a4e35': { lightness: 0.5316, saturation: 0.4767 },
  'short|ecad80|cb6820': { lightness: 0.5658, saturation: 0.5723 },
  'short|ecad80|afafaf': { lightness: 0.6175, saturation: 0.3963 },
  'short|9e5622|0e0e0e': { lightness: 0.2982, saturation: 0.3662 },
  'short|9e5622|e5d7a3': { lightness: 0.4618, saturation: 0.4934 },
  'short|9e5622|6a4e35': { lightness: 0.3570, saturation: 0.4465 },
  'short|9e5622|cb6820': { lightness: 0.3912, saturation: 0.5422 },
  'short|9e5622|afafaf': { lightness: 0.4429, saturation: 0.3662 },
  'short|763900|0e0e0e': { lightness: 0.2230, saturation: 0.5584 },
  'short|763900|e5d7a3': { lightness: 0.3867, saturation: 0.6857 },
  'short|763900|6a4e35': { lightness: 0.2819, saturation: 0.6388 },
  'short|763900|cb6820': { lightness: 0.3161, saturation: 0.7345 },
  'short|763900|afafaf': { lightness: 0.3678, saturation: 0.5584 },
  'long|f2d3b1|0e0e0e': { lightness: 0.3999, saturation: 0.2968 },
  'long|f2d3b1|e5d7a3': { lightness: 0.6791, saturation: 0.5143 },
  'long|f2d3b1|6a4e35': { lightness: 0.5004, saturation: 0.4337 },
  'long|f2d3b1|cb6820': { lightness: 0.5587, saturation: 0.5960 },
  'long|f2d3b1|afafaf': { lightness: 0.6469, saturation: 0.2968 },
  'long|ecad80|0e0e0e': { lightness: 0.3633, saturation: 0.3094 },
  'long|ecad80|e5d7a3': { lightness: 0.6425, saturation: 0.5270 },
  'long|ecad80|6a4e35': { lightness: 0.4638, saturation: 0.4463 },
  'long|ecad80|cb6820': { lightness: 0.5221, saturation: 0.6087 },
  'long|ecad80|afafaf': { lightness: 0.6103, saturation: 0.3094 },
  'long|9e5622|0e0e0e': { lightness: 0.2489, saturation: 0.2891 },
  'long|9e5622|e5d7a3': { lightness: 0.5281, saturation: 0.5066 },
  'long|9e5622|6a4e35': { lightness: 0.3494, saturation: 0.4260 },
  'long|9e5622|cb6820': { lightness: 0.4077, saturation: 0.5883 },
  'long|9e5622|afafaf': { lightness: 0.4959, saturation: 0.2891 },
  'long|763900|0e0e0e': { lightness: 0.1997, saturation: 0.4148 },
  'long|763900|e5d7a3': { lightness: 0.4789, saturation: 0.6324 },
  'long|763900|6a4e35': { lightness: 0.3002, saturation: 0.5517 },
  'long|763900|cb6820': { lightness: 0.3585, saturation: 0.7141 },
  'long|763900|afafaf': { lightness: 0.4467, saturation: 0.4148 },
};

const NEUTRAL_STATS: ColorStats = { lightness: 0.5, saturation: 0 };

export const getHeadColorStats = (
  hairVariant: string,
  skinColor: string,
  hairColor: string,
): ColorStats => {
  const hairLength = hairVariant.startsWith('long') ? 'long' : 'short';
  return HEAD_COLOR_STATS[`${hairLength}|${skinColor}|${hairColor}`] ?? NEUTRAL_STATS;
};
